[PP-21] Create home page
mrakofff/pointing-poker-fe pull request #16
Opened 2021-09-15 14:32 UTC by andreikaptsiuh

Task: https://andrei-lysiuk.atlassian.net/browse/PP-21
Description: 
 - create home page that will provide some app info 
 - page should include start new game button
 - add new page with room settings: name, vote system(disabled dropdown), create button
 Screenshots: 
![image](https://user-images.githubusercontent.com/76453952/133453040-06be25f8-d83a-4bc8-ad9d-d76736bc2ebf.png)
![image](https://user-images.githubusercontent.com/76453952/133667969-f4ea4f3c-b00b-45fc-864e-b4be085fc80d.png)

2021-09-15 14:41 UTC, MakFill commented on src/components/Input/Input.tsx
> +        name={name}
Отступы во всём файле не айс

2021-09-15 15:31 UTC, andreikaptsiuh commented on src/components/Input/Input.tsx
> +        name={name}
Попробовал пофиксить, но коммит не даёт отправить, и уже у меня нормально отображает, глянь ещё раз этот файл.  Это видимо какой-то баг

2021-09-15 15:49 UTC, mrakofff requested changes

2021-09-15 15:49 UTC, mrakofff commented on src/components/Modal/Modal.tsx
> +      onClick={(e) => closeModal(e.target as HTMLElement)}
use `closeModal` as callback without any wrapper functions

2021-09-15 15:49 UTC, mrakofff commented on src/components/Modal/Modal.tsx
> +    if (elem.classList.contains(styles.modal)) onClick();
- don't use inline `if` construction because of bad readability
- what a strange condition? To close on any click? we could add condition before return like `if(!show) {return null}`

2021-09-15 15:49 UTC, mrakofff commented on src/components/Modal/Modal.tsx
> +  children?: ReactNode;
Should it be non-optional coz modal will be useless without children?

2021-09-15 15:49 UTC, mrakofff commented on src/components/NewGameModal/NewGameModal.module.scss
> +      cursor: pointer;
could be moved to submit selector coz cursor will be changed only on hover

2021-09-15 15:49 UTC, mrakofff commented on src/components/NewGameModal/NewGameModal.tsx
> +            onChange={formHandler}
why handler is `formHandler` when you use it for input?

2021-09-15 15:49 UTC, mrakofff commented on src/pages/Home/Home.module.scss
> +  background-image: url(../../assets/images/logo.svg);
use absolute path

2021-09-15 15:49 UTC, mrakofff commented on src/components/Input/Input.module.scss
> +  height: 40px;
use `rem`s

2021-09-15 15:49 UTC, mrakofff commented on src/components/Input/Input.tsx
> +      id={label}
if you have only 1 input inside label you don't need any `id`s and `htmlFor `

2021-09-15 15:49 UTC, mrakofff commented on src/components/Input/Input.tsx
> +      type={type}
should `type` have default value like a `button`?

2021-09-15 15:49 UTC, mrakofff commented on src/components/Select/Select.tsx
> +export const Select: React.FC<ISelectProps> = ({
Perhaps it's better to use beautiful existed select?

2021-09-15 15:58 UTC, andreikaptsiuh commented on src/components/Modal/Modal.tsx
> +      onClick={(e) => closeModal(e.target as HTMLElement)}
fix

2021-09-15 16:03 UTC, andreikaptsiuh commented on src/components/Modal/Modal.tsx
> +    if (elem.classList.contains(styles.modal)) onClick();
It's be good?
![image](https://user-images.githubusercontent.com/76453952/133468662-c67b5f6f-c274-4a20-95c7-8fa7231ed648.png)

2021-09-15 16:04 UTC, andreikaptsiuh commented on src/components/Modal/Modal.tsx
> +  children?: ReactNode;
fix

2021-09-15 16:12 UTC, andreikaptsiuh commented on src/components/NewGameModal/NewGameModal.module.scss
> +      cursor: pointer;
fix

2021-09-15 16:14 UTC, andreikaptsiuh commented on src/components/Input/Input.module.scss
> +  height: 40px;
fix

2021-09-15 16:16 UTC, andreikaptsiuh commented on src/components/Input/Input.tsx
> +      id={label}
fix

2021-09-15 16:22 UTC, andreikaptsiuh commented on src/components/Input/Input.tsx
> +      type={type}
I don't know, but 'type' is required for this component's props

2021-09-15 16:30 UTC, andreikaptsiuh commented on src/components/Select/Select.tsx
> +export const Select: React.FC<ISelectProps> = ({
But then I have to write the same thing twice

2021-09-15 16:32 UTC, andreikaptsiuh commented on src/components/NewGameModal/NewGameModal.tsx
> +            onChange={formHandler}
fix

2021-09-15 16:33 UTC, andreikaptsiuh commented on src/pages/Home/Home.module.scss
> +  background-image: url(../../assets/images/logo.svg);
fix

2021-09-16 09:38 UTC, Praddby approved these changes

2021-09-16 11:44 UTC, mrakofff commented on src/components/Modal/Modal.tsx
> +    if (elem.classList.contains(styles.modal)) onClick();
please use one this variants:
- `if(<condition>){ //next-line <code> //next-line }`
- `<condition> && <code>`

2021-09-16 11:46 UTC, mrakofff commented on src/components/Input/Input.tsx
> +      type={type}
It will be better to use default `text` and on dev wanna pass another he will pass. No reasons to pass every type.

2021-09-16 15:20 UTC, andreikaptsiuh commented on src/components/Input/Input.tsx
> +      type={type}
fix

2021-09-16 15:22 UTC, andreikaptsiuh commented on src/components/Modal/Modal.tsx
> +    if (elem.classList.contains(styles.modal)) onClick();
fix

2021-09-16 17:42 UTC, andreikaptsiuh commented on src/components/Select/Select.tsx
> +export const Select: React.FC<ISelectProps> = ({
fix

2021-09-16 18:08 UTC, mrakofff requested changes

2021-09-16 18:08 UTC, mrakofff commented on src/components/NewGameModal/NewGameModal.module.scss
> +  padding: 30px;
use `rem`s

2021-09-16 18:08 UTC, mrakofff commented on src/components/NewGameModal/NewGameModal.module.scss
> +  margin-bottom: 20px;
use `rem`s

2021-09-16 18:08 UTC, mrakofff commented on src/components/NewGameModal/NewGameModal.module.scss
> +  height: 240px;
use `rem`s

2021-09-16 18:08 UTC, mrakofff commented on src/components/NewGameModal/NewGameModal.tsx
> +import { Input } from '../Input';
use `@` alias

2021-09-16 18:08 UTC, mrakofff commented on src/components/NewGameModal/NewGameModal.tsx
> +import { Modal } from '../Modal';
use `@` alias

2021-09-16 18:08 UTC, mrakofff commented on src/components/Input/Input.module.scss
> +.input {
add default `padding` to input

2021-09-16 18:08 UTC, mrakofff commented on src/components/Modal/Modal.tsx
> +  const closeModal: MouseEventHandler = (event) => {
update with generic and you don't need `as` on the next line:
`MouseEventHandler<HTMLDivElement>`

2021-09-16 18:36 UTC, andreikaptsiuh commented on src/components/NewGameModal/NewGameModal.module.scss
> +  padding: 30px;
fix

2021-09-16 18:37 UTC, andreikaptsiuh commented on src/components/NewGameModal/NewGameModal.module.scss
> +  margin-bottom: 20px;
fix

2021-09-16 18:38 UTC, andreikaptsiuh commented on src/components/NewGameModal/NewGameModal.module.scss
> +  height: 240px;
fix

2021-09-16 18:38 UTC, andreikaptsiuh commented on src/components/Input/Input.module.scss
> +.input {
fix

2021-09-16 18:42 UTC, andreikaptsiuh commented on src/components/NewGameModal/NewGameModal.tsx
> +import { Modal } from '../Modal';
fix

2021-09-16 18:42 UTC, andreikaptsiuh commented on src/components/NewGameModal/NewGameModal.tsx
> +import { Input } from '../Input';
fix

2021-09-17 07:24 UTC, andreikaptsiuh commented on src/components/Modal/Modal.tsx
> +  const closeModal: MouseEventHandler = (event) => {
It's don't work for 'div' elements

2021-09-17 09:46 UTC, MakFill commented on src/assets/images/logo.svg
> +<svg width="551" height="149" viewBox="0 0 551 149" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
поменяй может цвет лого на синий, черный не особо соотносится с нашим дизайном

2021-09-17 10:23 UTC, mrakofff approved these changes

2021-09-17 10:23 UTC, mrakofff commented on src/components/Input/Input.tsx
> +interface IImportProps {
Should it be `IInputProps`?)

2021-09-17 10:54 UTC, andreikaptsiuh commented on src/components/Input/Input.tsx
> +interface IImportProps {
Yes, I fix it

2021-09-17 11:16 UTC, merged