[PP-17] Integrate fe ws service with be connection
mrakofff/pointing-poker-fe pull request #17
Opened 2021-09-15 17:06 UTC by MakFill

Task: https://andrei-lysiuk.atlassian.net/browse/PP-17
Need to refactor socket events from BE with 'joinUser' and 'leaveUser' events

socket events: 

Event name | description
--- | ---|
'joinUser' | join user to room
'leaveUser' | leave user from room

2021-09-15 20:44 UTC, mrakofff requested changes

2021-09-15 20:44 UTC, mrakofff commented on src/WsService.ts
> +export enum SocketEvents {
- rename with`SocketEvent`
- move to `utils/enums/SocketEvent.ts`

2021-09-15 20:44 UTC, mrakofff commented on src/WsService.ts
> +  joinUser = 'joinUser',
Capitalize keys

2021-09-15 20:44 UTC, mrakofff commented on src/components/User/PanelUsers.tsx
> +  }, []);
unsubscribe from events on component `unmount`

2021-09-15 20:44 UTC, mrakofff commented on src/WsService.ts
>  const URL = process.env.REACT_APP_SOCKET_URL as string;
- rename file to `socketService` 
- move file `src/services/socketSevice` folder

2021-09-16 09:23 UTC, Praddby commented on src/components/User/User.tsx
> +        userType={user.role}
Тогда может и userType заменить на userRole?

2021-09-16 09:33 UTC, MakFill commented on src/components/User/User.tsx
> +        userType={user.role}
где?

2021-09-16 09:34 UTC, MakFill commented on src/WsService.ts
>  const URL = process.env.REACT_APP_SOCKET_URL as string;
done

2021-09-16 09:34 UTC, MakFill commented on src/WsService.ts
> +  joinUser = 'joinUser',
done

2021-09-16 09:34 UTC, MakFill commented on src/WsService.ts
> +export enum SocketEvents {
done

2021-09-16 09:41 UTC, Praddby commented on src/components/User/User.tsx
> +        userType={user.role}
32 строчка.
Раз переименовали свойство юзера type на role, то может надо переименовать userType на userRole?

2021-09-16 12:26 UTC, MakFill commented on src/components/User/User.tsx
> +        userType={user.role}
поменял

2021-09-17 10:16 UTC, mrakofff requested changes

2021-09-17 10:16 UTC, mrakofff commented on src/helpers/getSingleUser.ts
> +export class SingleUser {
- rename to `User` or `UserModel` that will realize `IUser` interface
- move it to `src/models/ <'User' or 'UserModel'>` folder
- add test to check data after creation

2021-09-17 10:16 UTC, mrakofff commented on src/components/User/PanelUsers.tsx
> +    socketService.on(SocketEvent.JoinUser, subscribeJoin);
- discuss user join message data contract and update callback
- add comments with discussed contract about userData from event

2021-09-17 11:38 UTC, MakFill commented on src/helpers/getSingleUser.ts
> +export class SingleUser {
done

2021-09-17 13:35 UTC, Praddby approved these changes

2021-09-17 14:57 UTC, andreikaptsiuh approved these changes

2021-09-17 17:05 UTC, mrakofff approved these changes

2021-09-17 17:05 UTC, mrakofff commented on src/models/UserModel/UserModel.test.ts
> +import { IUser } from '../../interfaces';
use `@` alias

2021-09-17 17:05 UTC, mrakofff commented on src/models/UserModel/UserModel.test.ts
> +  test('Class should be created', () => {
useless test

2021-09-17 17:05 UTC, mrakofff commented on src/models/UserModel/UserModel.ts
> +    this.name = `User${user.id.slice(0, 3)}`;
why do you set 2 times `this.name`?

2021-09-17 17:05 UTC, mrakofff commented on src/components/User/User.tsx
> +      selectedCardValue={user.score || ''}
not sure that it should be default here and `''` but okay

2021-09-17 17:05 UTC, mrakofff commented on src/components/User/PanelUsers.tsx
> +  const subscribeJoin = useCallback((user: IUser) => {
Not sure that BE will send you `IUser`, perhaps it could be another names of fields with needed data but let it postponed for BE realization finish

2021-09-17 17:29 UTC, MakFill commented on src/models/UserModel/UserModel.ts
> +    this.name = `User${user.id.slice(0, 3)}`;
removed

2021-09-17 17:29 UTC, MakFill commented on src/models/UserModel/UserModel.test.ts
> +  test('Class should be created', () => {
removed

2021-09-17 17:29 UTC, MakFill commented on src/models/UserModel/UserModel.test.ts
> +import { IUser } from '../../interfaces';
done

2021-09-17 17:31 UTC, merged