[PP-27] Create 404 page
mrakofff/pointing-poker-fe pull request #18
Opened 2021-09-16 17:02 UTC by MakFill

Task: https://andrei-lysiuk.atlassian.net/browse/PP-27

2021-09-16 17:13 UTC, mrakofff requested changes

2021-09-16 17:13 UTC, mrakofff commented on src/App.tsx
> +          <Route path={navMap.notFound()}>
You don't need any path because it works like `switch/case` and will catch path if no matches before

2021-09-16 17:13 UTC, mrakofff commented on src/untils/NavMap/NavMap.ts
> +  notFound = () => `${this.baseUrl}/*`;
Redundant path

2021-09-16 17:13 UTC, mrakofff commented on src/styles/variables.scss
> +$page-not-found-img: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzEwIiBoZWlnaHQ9IjEzMiIgdmlld0JveD0iMCAwIDMxMCAxMzIiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxjaXJjbGUgcj0i
Update with `.svg` file

2021-09-16 17:21 UTC, MakFill commented on src/App.tsx
> +          <Route path={navMap.notFound()}>
done

2021-09-16 17:21 UTC, MakFill commented on src/untils/NavMap/NavMap.ts
> +  notFound = () => `${this.baseUrl}/*`;
done

2021-09-16 17:21 UTC, MakFill commented on src/styles/variables.scss
> +$page-not-found-img: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzEwIiBoZWlnaHQ9IjEzMiIgdmlld0JveD0iMCAwIDMxMCAxMzIiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxjaXJjbGUgcj0i
done

2021-09-16 17:23 UTC, mrakofff approved these changes

2021-09-16 18:30 UTC, Praddby commented on src/pages/NotFound/NotFound.tsx
> +import classes from './NotFound.module.scss';
Везде в проекте, стиои подключаем как styles, тут как classes, можно запутаться)
Поменяй на styles

2021-09-16 18:30 UTC, Praddby commented on src/pages/NotFound/NotFound.tsx
> +      Go back
Наверное не "го бек", а "го хом" ? мы же отправляем на стартовую страницу.

2021-09-16 18:55 UTC, MakFill commented on src/pages/NotFound/NotFound.tsx
> +      Go back
https://planningpokeronline.com/jh

2021-09-16 18:57 UTC, MakFill commented on src/pages/NotFound/NotFound.tsx
> +import classes from './NotFound.module.scss';
поменял

2021-09-16 19:02 UTC, andreikaptsiuh approved these changes

2021-09-17 06:38 UTC, Praddby commented on src/pages/NotFound/NotFound.tsx
> +      Go back
Ok

2021-09-17 06:38 UTC, Praddby approved these changes

2021-09-17 07:28 UTC, merged