[PP-5] Create app theme variables
mrakofff/pointing-poker-fe pull request #2
Opened 2021-09-02 18:07 UTC by MakFill

**Task**: https://andrei-lysiuk.atlassian.net/browse/PP-5
**Description**: Create app theme variables

**Added**:
- added scss variables file with all variables that could be used in FE part of app
- added font-family
- added @import-normalize to style.scss

2021-09-02 18:42 UTC, Praddby approved these changes

2021-09-02 19:35 UTC, andreikaptsiuh approved these changes

2021-09-02 20:39 UTC, Praddby approved these changes

2021-09-03 10:23 UTC, mrakofff requested changes
Add some comment to fix

2021-09-03 10:23 UTC, mrakofff commented on .vscode/settings.json
> +{
add new pattern to `.gitignore`: `.vscode` and remove this files from PR

2021-09-03 10:23 UTC, mrakofff commented on .vscode/custom.css-data.json
> +{
Should be in `.gitignore`

2021-09-03 10:23 UTC, mrakofff commented on src/style.scss
> +  font-size: 14px;
Add Global size as `10px` and body `font-size: 1.4rem`

2021-09-03 10:23 UTC, mrakofff commented on normalize.css
> +@import-normalize;
it should be imported in global `style.css/scss` file not through the VScode

2021-09-03 10:58 UTC, MakFill commented on .vscode/settings.json
> +{
added

2021-09-03 10:58 UTC, MakFill commented on .vscode/custom.css-data.json
> +{
deleted

2021-09-03 10:58 UTC, MakFill commented on src/style.scss
> +  font-size: 14px;
html {
font-size: 10px;
}

body {
font-size: 1.4rem
}

2021-09-03 10:59 UTC, MakFill commented on normalize.css
> +@import-normalize;
done

2021-09-03 11:53 UTC, mrakofff approved these changes

2021-09-03 12:08 UTC, merged