[PP-26] Create some functionality to check if user is authorized
mrakofff/pointing-poker-fe pull request #20
Opened 2021-09-18 12:07 UTC by MakFill

Task: https://andrei-lysiuk.atlassian.net/browse/PP-26

created some functionality to check if user is authorized 
created modal to fill userName and finish joining

2021-09-18 12:17 UTC, andreikaptsiuh approved these changes

2021-09-18 19:25 UTC, mrakofff requested changes

2021-09-18 19:25 UTC, mrakofff commented on src/redux/store.ts
> +const middleware = getDefaultMiddleware({
`configureStore` allow callback as `middleware` key and could be moved inside
https://redux-toolkit.js.org/api/configureStore#parameters

2021-09-18 19:25 UTC, mrakofff commented on src/redux/store.ts
> +  immutableCheck: false,
it's better to turn on in dev mode. Will check if you modify store in reducer correctly

2021-09-18 19:25 UTC, mrakofff commented on src/redux/store.ts
> +  reducer: slice.reducer,
you will have a lot of reducers so use it as `Record`

2021-09-18 19:25 UTC, mrakofff commented on src/redux/store.ts
> +  devTools: process.env.NODE_ENV !== 'production',
Create helper `getEnvValue` and get it centralized by `env` variable name. Will be useful later

2021-09-18 19:25 UTC, mrakofff commented on src/redux/slice.ts
> +    user: {
separate to different reducers

2021-09-18 19:25 UTC, mrakofff commented on src/pages/Game/Game.tsx
> +  const { id } = useAppSelector((state) => state.user);
add `selectors` folder inside `redux` folder and create selectors with the help of `createSelector` function

2021-09-18 19:25 UTC, mrakofff commented on src/redux/reduxHooks.ts
> +import { TypedUseSelectorHook, useDispatch, useSelector } from 'react-redux';
You don't need `redux` prefix before in file name

2021-09-18 19:25 UTC, mrakofff commented on src/components/Modals/ChooseUserNameModal.tsx
> +          <FormControlLabel
1. It should be disabled 
2. if you are using any ui kit you should discuss with team and make all components from one kit

2021-09-18 19:25 UTC, mrakofff commented on src/components/Modal/Modal.module.scss
> +  z-index: 10;
I think you should add `className` prop to default modal to be able to override this value

2021-09-20 10:50 UTC, MakFill commented on src/components/Modal/Modal.module.scss
> +  z-index: 10;
why? It's simply any modal should be upper other fields. No one modal should be under any fields

2021-09-20 13:35 UTC, MakFill commented on src/components/Modals/ChooseUserNameModal.tsx
> +          <FormControlLabel
disabled

2021-09-20 13:35 UTC, MakFill commented on src/redux/reduxHooks.ts
> +import { TypedUseSelectorHook, useDispatch, useSelector } from 'react-redux';
refactored

2021-09-20 13:35 UTC, MakFill commented on src/pages/Game/Game.tsx
> +  const { id } = useAppSelector((state) => state.user);
refactored

2021-09-20 13:35 UTC, MakFill commented on src/redux/slice.ts
> +    user: {
refactored

2021-09-20 13:35 UTC, MakFill commented on src/redux/store.ts
> +  devTools: process.env.NODE_ENV !== 'production',
refactored

2021-09-20 13:35 UTC, MakFill commented on src/redux/store.ts
> +  reducer: slice.reducer,
refactored

2021-09-20 13:35 UTC, MakFill commented on src/redux/store.ts
> +  immutableCheck: false,
refactored

2021-09-20 13:35 UTC, MakFill commented on src/redux/store.ts
> +const middleware = getDefaultMiddleware({
refactored

2021-09-22 17:11 UTC, MakFill commented on src/helpers/useUserData.ts
> +}
Такой принцип?

2021-09-22 18:52 UTC, mrakofff requested changes

2021-09-22 18:52 UTC, mrakofff commented on src/components/Modal/Modal.module.scss
> +  z-index: 10;
because when you have another absolute or fixed elements you will not be able to update this parameter from outside styles

2021-09-22 18:52 UTC, mrakofff commented on src/pages/Game/Game.tsx
> +      <ChooseUserNameModal show={modal} setModal={setModal} onClick={showModal} />
we should check if user is authorized before showing `newGameModal`. I think it should be some condition on this button. And if creating room was success and we have stored `userId` we should show modal with new room settings(if we creating user we should show room automatically)

2021-09-24 08:48 UTC, Praddby commented on src/helpers/useUserData.ts
> +    const user: IUser = await http.get(`/api/users?userId=${id}`);
На бе другой путь, исправь тут или там

2021-09-24 13:08 UTC, MakFill commented on src/components/Modal/Modal.module.scss
> +  z-index: 10;
deleted coz redudant

2021-09-30 19:45 UTC, mrakofff requested changes

2021-09-30 19:45 UTC, mrakofff commented on src/components/Modal/Modal.tsx
> +          [styles.modal_close]: !show,
Could we add `close` styles by default and `opened` only with `classname`?

2021-09-30 19:45 UTC, mrakofff commented on src/components/Modals/ChooseUserNameModal.tsx
> +    httpClient.url = 'http://localhost:3000';
stop overriding `baseUrl`. Pass full BE url.

2021-09-30 19:45 UTC, mrakofff commented on src/components/Modals/ChooseUserNameModal.tsx
> +    const user: IUserFromBE = await httpClient.http.post('/api/users',
this funtionality should works inside `thunk`

2021-09-30 19:45 UTC, mrakofff commented on src/components/Modals/ChooseUserNameModal.tsx
> +  const inputsHandler: ChangeEventHandler<HTMLInputElement> = (event) => {
why inputs when you use it for one input?

2021-09-30 19:45 UTC, mrakofff commented on src/helpers/checkUserIdandRoomId.ts
> +httpClient.url = 'http://localhost:3000';
remove this setter and stop override `baseUrl`

2021-09-30 19:45 UTC, mrakofff commented on src/helpers/checkUserIdandRoomId.ts
> +    const user: IUser = await http.get(`/api/users/${+id}`);
No reason to parse id to number coz url is a string

2021-09-30 19:45 UTC, mrakofff commented on src/helpers/checkUserIdandRoomId.ts
> +async function getUserData() {
move this to redux acton

2021-09-30 19:45 UTC, mrakofff commented on src/helpers/checkUserIdandRoomId.ts
> +export async function checkUserIdandRoomId(
make all requests inside redux action

2021-09-30 19:45 UTC, mrakofff commented on src/pages/Game/Game.tsx
> +    if (roomId) {
why we need to push to `games/:roomId`  when we already there

2021-09-30 19:45 UTC, mrakofff commented on src/pages/Game/Game.tsx
> +    checkUserIdandRoomId(dispatch, history);
you should run chis check on some pages and show protected pages content only if `userId` is defined. also this actions should be splitted into 2 independent and be called on different conditions

2021-09-30 19:45 UTC, mrakofff commented on src/components/Modals/NewGameModal.tsx
> +    dispatch(roomStateActions.setRoomId(mockRoomId));
on submit you will call `createRoom` action that will call API and update room state

2021-09-30 19:45 UTC, mrakofff commented on src/components/Modals/NewGameModal.tsx
> +    voteSystem: voteOptions[0].value,
you need only `roomTitle`. Another could be hardcoded

2021-09-30 19:45 UTC, mrakofff commented on src/components/Input/Input.tsx
> +    required
why it should be required, add additional props and pass if you need. It shouldn't be required by default

2021-09-30 19:45 UTC, mrakofff commented on src/components/Modal/Modal.tsx
> +  styleName?: string;
perhaps it should be `className`

2021-09-30 21:43 UTC, Praddby approved these changes

2021-10-01 09:04 UTC, MakFill commented on src/components/Modal/Modal.tsx
> +          [styles.modal_close]: !show,
No, but refactored

2021-10-01 09:04 UTC, MakFill commented on src/components/Modals/ChooseUserNameModal.tsx
> +    httpClient.url = 'http://localhost:3000';
passed

2021-10-01 09:06 UTC, MakFill commented on src/components/Modals/ChooseUserNameModal.tsx
> +  const inputsHandler: ChangeEventHandler<HTMLInputElement> = (event) => {
renamed

2021-10-01 09:07 UTC, MakFill commented on src/helpers/checkUserIdandRoomId.ts
> +httpClient.url = 'http://localhost:3000';
removed

2021-10-01 09:08 UTC, MakFill commented on src/helpers/checkUserIdandRoomId.ts
> +    const user: IUser = await http.get(`/api/users/${+id}`);
removed plus

2021-10-01 09:20 UTC, MakFill commented on src/components/Modals/NewGameModal.tsx
> +    voteSystem: voteOptions[0].value,
?

2021-10-01 09:23 UTC, MakFill commented on src/components/Input/Input.tsx
> +    required
both Input component instances required. What is the point of putting logic into props if it is required for all instances?

2021-10-01 09:23 UTC, MakFill commented on src/components/Modal/Modal.tsx
> +  styleName?: string;
renamed

2021-10-01 10:21 UTC, MakFill commented on src/helpers/checkUserIdandRoomId.ts
> +async function getUserData() {
done

2021-10-01 10:21 UTC, MakFill commented on src/helpers/checkUserIdandRoomId.ts
> +export async function checkUserIdandRoomId(
done

2021-10-01 10:22 UTC, MakFill commented on src/pages/Game/Game.tsx
> +    if (roomId) {
refactored

2021-10-01 10:33 UTC, MakFill commented on src/components/Modals/NewGameModal.tsx
> +    dispatch(roomStateActions.setRoomId(mockRoomId));
changed

2021-10-01 15:30 UTC, MakFill commented on src/pages/Game/Game.tsx
> +    checkUserIdandRoomId(dispatch, history);
done

2021-10-01 17:45 UTC, mrakofff requested changes

2021-10-01 17:45 UTC, mrakofff commented on src/components/Input/Input.tsx
> +    required
user description input is optional

2021-10-01 17:45 UTC, mrakofff commented on src/components/Modal/Modal.tsx
> +          [styles.modal_close]: !show,
I think `className` from props should be last one to be able to override styles from outside

2021-10-01 17:45 UTC, mrakofff commented on src/components/Modals/NewGameModal.tsx
> +    voteSystem: voteOptions[0].value,
You use Object as state where 2 from 3 values are mocks, do you need object at all?

2021-10-01 17:45 UTC, mrakofff commented on src/utils/NavMap/NavMap.ts
> +  lobby = () => `${this.baseUrl}/new-game`;
rename key to `newGame`

2021-10-01 17:45 UTC, mrakofff commented on src/store/reducers/roomStateReducer.ts
> +    .addCase(roomStateActions.getRoomByUrl.fulfilled, (state, action) => ({ ...state, roomId: action.payload }))
you could mutate directly `state.roomId = action.payload` without return. toolkit will do it by himself

2021-10-01 17:45 UTC, mrakofff commented on src/pages/NewGame/NewGame.tsx
> +    dispatch(userActions.getUserDataByLS(id)).then((event) => {
you could get `userId` inside thunk

2021-10-01 18:00 UTC, MakFill commented on src/components/Modal/Modal.tsx
> +          [styles.modal_close]: !show,
One of Modals show/hides via useState, second no

2021-10-01 18:01 UTC, MakFill commented on src/components/Modals/NewGameModal.tsx
> +    voteSystem: voteOptions[0].value,
It's default values, not mock

2021-10-01 18:02 UTC, MakFill commented on src/components/Input/Input.tsx
> +    required
refactored

2021-10-02 10:02 UTC, MakFill commented on src/components/Modals/ChooseUserNameModal.tsx
> +    const user: IUserFromBE = await httpClient.http.post('/api/users',
done

2021-10-02 16:46 UTC, mrakofff requested changes

2021-10-02 16:46 UTC, mrakofff commented on src/helpers/delay.ts
> +export async function delay(payload: any, ms: number): Promise<any> {
you could add default `ms` to simplify calling if you don't need some special time

2021-10-02 16:46 UTC, mrakofff commented on src/helpers/delay.ts
> +export async function delay(payload: any, ms: number): Promise<any> {
any could be replaced with `P` to say that return type will be the same as payload type

2021-10-02 16:46 UTC, mrakofff commented on src/pages/Game/Game.tsx
> +    dispatch(userActions.getUserDataByLS()).then((event) => {
why is it still not inside thunk?

2021-10-02 16:46 UTC, mrakofff commented on src/store/actions/roomStateAction.ts
> +          return rejectWithValue('Error witn room');
could you throw an error and call `history.push` only in catch?

2021-10-02 16:46 UTC, mrakofff commented on src/store/actions/roomStateAction.ts
> +        history.push('/newGame');
you have `new-game` page inside `navMap`

2021-10-02 16:46 UTC, mrakofff commented on src/store/actions/userActions.ts
> +          history.push('/404');
- use `navmap`
- and same question with throwing error and exclude pushing to 404 code duplicates

2021-10-02 16:46 UTC, mrakofff commented on src/utils/NavMap/NavMap.ts
> +  lobby = () => `${this.baseUrl}/newGame`;
sync key with value

2021-10-02 17:06 UTC, MakFill commented on src/store/actions/roomStateAction.ts
> +        history.push('/newGame');
refactored

2021-10-02 17:07 UTC, MakFill commented on src/store/actions/userActions.ts
> +          history.push('/404');
refactored

2021-10-02 17:07 UTC, MakFill commented on src/utils/NavMap/NavMap.ts
> +  lobby = () => `${this.baseUrl}/newGame`;
refactored

2021-10-02 17:15 UTC, MakFill commented on src/store/actions/roomStateAction.ts
> +          return rejectWithValue('Error witn room');
refactored

2021-10-02 19:33 UTC, mrakofff approved these changes

2021-10-03 09:17 UTC, merged