[PP-28] Update application structure
mrakofff/pointing-poker-fe pull request #23
Opened 2021-09-19 16:58 UTC by MakFill

Task: https://andrei-lysiuk.atlassian.net/browse/PP-28

2021-09-19 17:11 UTC, mrakofff requested changes

2021-09-19 17:11 UTC, mrakofff commented on src/helpers/getEnvValue.ts
> +export function getEnvValue(): string {
this function should return `env` variable by provided `env` name. F.e.: `NODE_ENV` -> `process.env.NODE_ENV`

2021-09-19 17:11 UTC, mrakofff commented on src/store/reducers/userReducer.ts
> +} from '../actions/userActions';
use `alias`

2021-09-19 17:11 UTC, mrakofff commented on src/store/reducers/userReducer.ts
> +  user: {
split to different reducers: `user`, `game`

2021-09-19 17:11 UTC, mrakofff commented on src/store/selectors/userSelectors.ts
> +export const gameSettings = createSelector(settings, (state) => state);
combine user selectors as `userSelectors` object and make one export to simplify imports

2021-09-19 17:11 UTC, mrakofff commented on src/store/store.ts
> +  middleware: getDefaultMiddleware({
could be  `middleware: (getDefaultMiddleware) => getDefaultMiddleware(<code>)` but it's okay too

2021-09-19 18:26 UTC, MakFill commented on src/store/selectors/userSelectors.ts
> +export const gameSettings = createSelector(settings, (state) => state);
done

2021-09-19 18:26 UTC, MakFill commented on src/store/reducers/userReducer.ts
> +  user: {
done

2021-09-19 18:26 UTC, MakFill commented on src/store/reducers/userReducer.ts
> +} from '../actions/userActions';
done

2021-09-19 18:26 UTC, MakFill commented on src/helpers/getEnvValue.ts
> +export function getEnvValue(): string {
done

2021-09-19 18:55 UTC, mrakofff requested changes

2021-09-19 18:55 UTC, mrakofff commented on src/store/reducers/userReducer.ts
> +  user: {
now your reducer `userReducer.ts` has 2 reducers inside
and you don't need `user` nesting

2021-09-19 18:55 UTC, mrakofff commented on src/store/selectors/userSelectors.ts
> +  userId: createSelector(user, (state) => state.id),
if you do not use this selectors do not create them

2021-09-19 18:55 UTC, mrakofff commented on src/store/selectors/userSelectors.ts
> +  gameSettings: createSelector(settings, (state) => state),
`gameSettings` selector inside `userSelectors`?

2021-09-19 18:55 UTC, mrakofff commented on src/utils/interfaces/index.ts
> +export * from './interfaces';
each interface should be in separate named file and reexported in `index` file

2021-09-19 20:04 UTC, MakFill commented on src/store/selectors/userSelectors.ts
> +  userId: createSelector(user, (state) => state.id),
delete all selectors?

2021-09-19 20:12 UTC, MakFill commented on src/utils/interfaces/index.ts
> +export * from './interfaces';
done

2021-09-19 20:12 UTC, MakFill commented on src/store/selectors/userSelectors.ts
> +  gameSettings: createSelector(settings, (state) => state),
replaced

2021-09-19 20:33 UTC, mrakofff requested changes

2021-09-19 20:33 UTC, mrakofff commented on src/store/selectors/userSelectors.ts
> +  userId: createSelector(user, (state) => state.id),
leave user data selector(`state.user`)

2021-09-19 20:33 UTC, mrakofff commented on src/store/store.ts
> +  reducer: { userReducer, gameReducer },
change name without `reducer` postfix
![image](https://user-images.githubusercontent.com/21972136/133942107-b6e4a855-b21f-4ebd-bb0d-5439d88c2ca2.png)
https://redux.js.org/style-guide/style-guide#name-state-slices-based-on-the-stored-data

2021-09-19 20:33 UTC, mrakofff commented on src/store/selectors/userSelectors.ts
> +export const gameSettings = createSelector((state: RootState) => state.gameReducer, (state) => state);
split reducers and selectors to diff files according to their names and logic(f.e. user -> user logic, game -> game logic)

2021-09-20 07:28 UTC, mrakofff approved these changes

2021-09-20 08:37 UTC, andreikaptsiuh approved these changes

2021-09-20 08:45 UTC, Praddby approved these changes

2021-09-20 10:02 UTC, merged