[PP-38] add handlers for messages actions
mrakofff/pointing-poker-fe pull request #26
Opened 2021-09-26 10:30 UTC by MakFill

Task: https://andrei-lysiuk.atlassian.net/browse/PP-38
**Created:** 
- messages reducer
- components and containers: `Chat`, `Message`, `SendMessageForm`

**Added and integrated to components above:** 
- actions to get all messages after user join/create room
- handlers to catch all socket events related to messages.

**From BE we get message with:**
 -  id: number;
 - text: string;
 - date: Date;
 - userId: number;
 - roomId: string;
 - name: string;

2021-09-26 11:47 UTC, mrakofff requested changes

2021-09-26 11:47 UTC, mrakofff commented on src/components/Message/Message.tsx
> +export const Message: React.FC<IMessage> = ({ userName, message }): JSX.Element => (
Should you describe function return type or TS with `infer` it by himself?

2021-09-26 11:47 UTC, mrakofff commented on src/components/User/User.module.scss
> +  height: 50vh;
If we have some dependencies from this size perhaps it's better to move this value to `variables`? Or we have no dependencies?

2021-09-26 11:47 UTC, mrakofff commented on src/containers/Chat/Chat.module.scss
> +  height: 50vh;
The same as for User `size` should the be the same?

2021-09-26 11:47 UTC, mrakofff commented on src/containers/Chat/Chat.tsx
> +    getMessagesByRoomId(room);
why do you call dispatch from helper but don't use `thunk` middleware?
You should call something like `dispatch(messagesActions.getAllMessagesByRoomId())` and do all the stuff there

2021-09-26 11:47 UTC, mrakofff commented on src/containers/Chat/Chat.tsx
> +          message.id > 0
what is this condition for?

2021-09-26 11:47 UTC, mrakofff commented on src/helpers/getMessagesByRoomId.ts
> +import { getMessages } from '@/store/actions/messageActions';
reduce path with `index` file reexport

2021-09-26 11:47 UTC, mrakofff commented on src/helpers/getMessagesByRoomId.ts
> +  const messagesFromBE: IMessage[] = await httpClient.http.get(`/api/messages?roomId=${roomId}`);
move this logic to `thunk` middleware

2021-09-26 11:47 UTC, mrakofff commented on src/pages/Game/Game.tsx
> +      <section>
Perhaps it's better to set sizes for `section` and update sizes of children with `100%`?

2021-09-26 11:47 UTC, mrakofff commented on src/store/actions/messageActions.ts
> +export const addMessage = createAction<IMessage>('addMessage');
group up actions in one object to reduce number of imports

2021-09-26 11:47 UTC, mrakofff commented on src/store/store.ts
> +import { messages } from './reducers/messagesReducer';
add reexports for `index` file and imports will be less

2021-09-26 11:47 UTC, mrakofff commented on src/store/selectors/messageSelector.ts
> +export const messageSelector = createSelector((state: RootState) => state.messages, (messages) => messages);
create one object `messagesSelectors` and add selector as key.

2021-09-26 11:47 UTC, mrakofff commented on src/store/reducers/userReducer.ts
> +  id: NaN,
I think it's better to use previous value, and all ids from BE convert to strings. More easy to work with strings

2021-09-26 11:47 UTC, mrakofff commented on src/containers/SendMessageForm/SendMessageForm.tsx
> +export const SendMessageForm = (): JSX.Element => {
if you add type of `SendMessageForm` as `FC` should you use return type?

2021-09-26 11:50 UTC, MakFill commented on src/components/User/User.module.scss
> +  height: 50vh;
No dependencies just half of the screen

2021-09-26 11:51 UTC, MakFill commented on src/containers/Chat/Chat.module.scss
> +  height: 50vh;
No. 50% - users, 40% - chat, other - send message form

2021-09-26 11:53 UTC, MakFill commented on src/components/Message/Message.tsx
> +export const Message: React.FC<IMessage> = ({ userName, message }): JSX.Element => (
removed

2021-09-26 11:55 UTC, MakFill commented on src/containers/Chat/Chat.tsx
> +          message.id > 0
There is default initial state messages: [{ userName: '', message: '', id: '' }}]

2021-09-26 11:58 UTC, MakFill commented on src/helpers/getMessagesByRoomId.ts
> +import { getMessages } from '@/store/actions/messageActions';
done

2021-09-26 12:04 UTC, MakFill commented on src/pages/Game/Game.tsx
> +      <section>
done

2021-09-26 12:43 UTC, MakFill commented on src/store/actions/messageActions.ts
> +export const addMessage = createAction<IMessage>('addMessage');
done

2021-09-26 13:20 UTC, MakFill commented on src/store/store.ts
> +import { messages } from './reducers/messagesReducer';
done

2021-09-26 13:23 UTC, MakFill commented on src/store/selectors/messageSelector.ts
> +export const messageSelector = createSelector((state: RootState) => state.messages, (messages) => messages);
done

2021-09-26 13:25 UTC, mrakofff commented on src/containers/Chat/Chat.tsx
> +          message.id > 0
could it be empty `Array`? why message list has mock data?

2021-09-26 13:25 UTC, MakFill commented on src/store/reducers/userReducer.ts
> +  id: NaN,
done

2021-09-26 13:27 UTC, MakFill commented on src/containers/SendMessageForm/SendMessageForm.tsx
> +export const SendMessageForm = (): JSX.Element => {
added

2021-09-26 14:43 UTC, MakFill commented on src/containers/Chat/Chat.tsx
> +    getMessagesByRoomId(room);
done

2021-09-26 14:43 UTC, MakFill commented on src/helpers/getMessagesByRoomId.ts
> +  const messagesFromBE: IMessage[] = await httpClient.http.get(`/api/messages?roomId=${roomId}`);
done

2021-09-27 06:50 UTC, MakFill commented on src/containers/Chat/Chat.tsx
> +          message.id > 0
removed mock data

2021-09-27 20:47 UTC, mrakofff requested changes

2021-09-27 20:47 UTC, mrakofff commented on src/containers/SendMessageForm/SendMessageForm.module.scss
> +    width: fit-content;
could we use flex model for styles?

2021-09-27 20:47 UTC, mrakofff commented on src/containers/SendMessageForm/SendMessageForm.tsx
> +import { SendMessageModel } from '@/models/SendMessageModel/SendMessageModel';
reduce import with `index` reexport

2021-09-27 20:47 UTC, mrakofff commented on src/containers/SendMessageForm/SendMessageForm.tsx
> +import { socketService } from '@/services/socketService';
reduce import with `index` reexport

2021-09-27 20:47 UTC, mrakofff commented on src/store/index.ts
> +export { useAppDispatch } from './store';
could be moved to 1-st line export coz the same file

2021-09-27 20:47 UTC, mrakofff commented on src/store/reducers/messagesReducer.ts
> +import { addMessage, getMessages } from '@/store/actions/messageActions';
reduce import with `index` reexport

2021-09-27 20:47 UTC, mrakofff commented on src/store/reducers/userReducer.ts
>  } from '@/store/actions/userActions';
reduce import with `index` reexport

2021-09-27 20:47 UTC, mrakofff commented on src/utils/interfaces/IUser.ts
> +  roomId: string;
I think in game context it's redundant coz we don't monitor more than 1 game in one room

2021-09-27 20:47 UTC, mrakofff commented on src/utils/interfaces/IUser.ts
> +  roomUserId: string
this field is equal to `IUser['id']`

2021-09-27 20:47 UTC, mrakofff commented on src/utils/interfaces/IRoomMember.ts
> +export interface IRoomMember {
Duplicate for `IUser`

2021-09-27 20:47 UTC, mrakofff commented on src/models/SendMessageModel/SendMessageModel.ts
> +export class SendMessageModel {
Should Model implements Interface?

2021-09-27 20:47 UTC, mrakofff commented on src/models/SendMessageModel/SendMessageModel.ts
> +import { ISendMessage } from '@/utils/interfaces';
Perhaps it's better to rename to `INewMessage`?

2021-09-27 20:47 UTC, mrakofff commented on src/models/UserModel/RoomMemberModel.ts
> +export class RoomMemberModel {
redundant model

2021-09-27 20:47 UTC, mrakofff commented on src/pages/Game/Game.module.scss
> +    min-width: calc(100vw - 80rem);
why it's 80? is it sum of somehting? if yes perhaps it's better to use variables?

2021-09-27 20:47 UTC, mrakofff commented on src/store/reducers/roomMembersReducer.ts
> +    .addCase(roomMembersActions.addRoomMembers, (state, action) => {
Should we add action for `user_leave_the_chat` or it will be written later?

2021-09-27 20:47 UTC, mrakofff commented on src/store/reducers/roomState.ts
> +const initialStateGame = {
rename to `initialState` no need to use additional prefix coz it's local variable

2021-09-27 20:47 UTC, mrakofff commented on src/store/reducers/userReducer.ts
> +    .addCase(userActions.addUserId, (state, action) => {
As i remember we will get all user data from 1 request? Do we need separate actions?

2021-09-27 20:47 UTC, mrakofff commented on src/store/reducers/roomMembersReducer.ts
> +const initialStateRoomMembers: IUser[] = [];
Could we simplify the name with `initialState`?

2021-09-27 20:47 UTC, mrakofff commented on src/store/reducers/roomMembersReducer.ts
> +export const roomMembers = createReducer(initialStateRoomMembers, (builder) => {
Perhaps it's better to rename with `players` or `participants`?

2021-09-27 20:47 UTC, mrakofff commented on src/store/selectors/roomStateSelector.ts
> +  gameName: createSelector((state: RootState) => state.roomState, (state) => state.roomTitle),
`gameName` => `roomTitle` ?

2021-09-27 20:47 UTC, mrakofff commented on src/store/selectors/roomStateSelector.ts
> +  dealerRights: createSelector((state: RootState) => state.roomState, (state) => state.dealerRights),
do we have this data on BE?

2021-09-27 20:47 UTC, mrakofff commented on src/store/selectors/userSelector.ts
> +import { createSelector } from '@reduxjs/toolkit';
Why did you rename file if you have a lot of selectors inside?

2021-09-27 20:47 UTC, mrakofff commented on src/store/selectors/roomStateSelector.ts
> +import { createSelector } from '@reduxjs/toolkit';
the same question with filename

2021-09-27 20:47 UTC, mrakofff commented on src/store/reducers/roomState.ts
> +    .addCase(addRoomState, (state, action) => {
Could you destructure action to `payload` and `type`? And then reduce 4 rows nesting

2021-09-27 20:47 UTC, mrakofff commented on src/components/User/PanelUsers.tsx
> +import { RoomMemberModel } from '@/models/UserModel';
Use `UserModel` if they are the same

2021-09-27 20:47 UTC, mrakofff commented on src/components/User/PanelUsers.tsx
> +    setUsers((usrs) => usrs.filter((usr) => usr.userId !== id));
Is it needed updates? we have redux for user storing so this code is out of date, do you need to update it?

2021-09-27 20:47 UTC, mrakofff commented on src/containers/Chat/Chat.tsx
> +import { socketService } from '@/services/socketService';
reduce import

2021-09-27 20:47 UTC, mrakofff commented on src/models/MessageModel/MessageModel.ts
> +    this.roomId = message.roomId;
we will not get messages from another room, so this field is redundant

2021-09-27 20:47 UTC, mrakofff commented on src/models/MessageModel/MessageModel.ts
> +    this.name = message.name;
What is message name?

2021-09-27 20:47 UTC, mrakofff commented on src/pages/Game/Game.tsx
> +import { Chat } from '@/containers/Chat';
reduce import path

2021-09-27 20:47 UTC, mrakofff commented on src/store/actions/addRoomState.ts
> +export const addRoomState = createAction<IRoomState>('addGameSettings');
`addGameSettings` => `addRoomState`
But another question: will we have this action? or it will be `getRoomState/setRoomState`?

2021-09-27 20:47 UTC, mrakofff commented on src/helpers/getMessagesByRoomId.ts
> +export function getMessagesByRoomId(roomId: string) {
why you move this method to helpers when you could store it in `messagesActions`?
```
const updateUser = createAsyncThunk(
  'users/update',
  async (userData, { rejectWithValue }) => {
    const { id, ...fields } = userData
    try {
      const response = await userAPI.updateById(id, fields)
      return response.data.user
    } catch (err) {
      // Use `err.response.data` as `action.payload` for a `rejected` action,
      // by explicitly returning it using the `rejectWithValue()` utility
      return rejectWithValue(err.response.data)
    }
  }
)
```

example from https://redux-toolkit.js.org/api/createAsyncThunk (under the `handling-thunk-errors` part)

2021-09-27 20:47 UTC, mrakofff commented on src/containers/Chat/Chat.tsx
> +    dispatch<any>(getMessagesByRoomId(roomId));
why is it `<any>`?

2021-09-27 20:47 UTC, mrakofff commented on src/containers/SendMessageForm/SendMessageForm.tsx
> +    const sendedMessage = new SendMessageModel({
should it be `newMessage`?

2021-09-27 20:47 UTC, mrakofff commented on src/containers/SendMessageForm/SendMessageForm.tsx
> +      <input
As I remember we habe Input component, could we reuse it here?

2021-09-27 20:47 UTC, mrakofff commented on src/helpers/getMessageByMessageFromBE.ts
> +import { MessageModel } from '@/models/MessageModel';
reduce import name

2021-09-27 20:47 UTC, mrakofff commented on src/store/actions/messageActions.ts
> +  addMessage: createAction<IMessage>('addMessage'),
add prefix to `actionType` something like `[MESSAGES]:` or `messages/` or another to increase actions readability in devtools

2021-09-27 20:47 UTC, mrakofff commented on src/store/actions/roomMembersActions.ts
> +  addRoomMembers: createAction<IUser[]>('addRoomMembers'),
`actionType` prefix

2021-09-28 09:14 UTC, MakFill commented on src/containers/SendMessageForm/SendMessageForm.module.scss
> +    width: fit-content;
Yes, what is the problem?

2021-09-28 09:16 UTC, MakFill commented on src/containers/SendMessageForm/SendMessageForm.tsx
> +import { SendMessageModel } from '@/models/SendMessageModel/SendMessageModel';
done

2021-09-28 09:20 UTC, MakFill commented on src/containers/SendMessageForm/SendMessageForm.tsx
> +import { socketService } from '@/services/socketService';
done

2021-09-28 09:20 UTC, MakFill commented on src/store/index.ts
> +export { useAppDispatch } from './store';
done

2021-09-28 09:21 UTC, MakFill commented on src/store/reducers/messagesReducer.ts
> +import { addMessage, getMessages } from '@/store/actions/messageActions';
done

2021-09-28 09:22 UTC, MakFill commented on src/store/reducers/userReducer.ts
>  } from '@/store/actions/userActions';
done

2021-09-28 09:22 UTC, MakFill commented on src/utils/interfaces/IUser.ts
> +  roomId: string;
removed

2021-09-28 09:23 UTC, MakFill commented on src/utils/interfaces/IUser.ts
> +  roomUserId: string
removed

2021-09-28 09:23 UTC, MakFill commented on src/utils/interfaces/IRoomMember.ts
> +export interface IRoomMember {
removed

2021-09-28 09:25 UTC, MakFill commented on src/models/SendMessageModel/SendMessageModel.ts
> +export class SendMessageModel {
changed

2021-09-28 09:25 UTC, MakFill commented on src/models/SendMessageModel/SendMessageModel.ts
> +import { ISendMessage } from '@/utils/interfaces';
removed

2021-09-28 09:29 UTC, MakFill commented on src/models/UserModel/RoomMemberModel.ts
> +export class RoomMemberModel {
removed

2021-09-28 09:37 UTC, MakFill commented on src/pages/Game/Game.module.scss
> +    min-width: calc(100vw - 80rem);
removed field

2021-09-28 09:38 UTC, MakFill commented on src/store/reducers/roomMembersReducer.ts
> +    .addCase(roomMembersActions.addRoomMembers, (state, action) => {
later. It's another task

2021-09-28 09:40 UTC, MakFill commented on src/store/reducers/roomState.ts
> +const initialStateGame = {
done

2021-09-28 09:45 UTC, MakFill commented on src/store/reducers/userReducer.ts
> +    .addCase(userActions.addUserId, (state, action) => {
role and score from different requests, only id and name in one request

2021-09-28 09:55 UTC, MakFill commented on src/store/reducers/roomMembersReducer.ts
> +const initialStateRoomMembers: IUser[] = [];
done

2021-09-28 09:59 UTC, MakFill commented on src/store/reducers/roomMembersReducer.ts
> +export const roomMembers = createReducer(initialStateRoomMembers, (builder) => {
renamed to members

2021-09-28 10:00 UTC, MakFill commented on src/store/selectors/roomStateSelector.ts
> +  gameName: createSelector((state: RootState) => state.roomState, (state) => state.roomTitle),
renamed

2021-09-28 10:01 UTC, MakFill commented on src/store/selectors/roomStateSelector.ts
> +  dealerRights: createSelector((state: RootState) => state.roomState, (state) => state.dealerRights),
yes we should have

2021-09-28 10:02 UTC, MakFill commented on src/store/selectors/userSelector.ts
> +import { createSelector } from '@reduxjs/toolkit';
renamed

2021-09-28 10:02 UTC, MakFill commented on src/store/selectors/roomStateSelector.ts
> +import { createSelector } from '@reduxjs/toolkit';
renamed

2021-09-28 10:10 UTC, MakFill commented on src/store/reducers/roomState.ts
> +    .addCase(addRoomState, (state, action) => {
done

2021-09-28 10:10 UTC, MakFill commented on src/components/User/PanelUsers.tsx
> +import { RoomMemberModel } from '@/models/UserModel';
done

2021-09-28 10:38 UTC, MakFill commented on src/components/User/PanelUsers.tsx
> +    setUsers((usrs) => usrs.filter((usr) => usr.userId !== id));
updated

2021-09-28 10:39 UTC, MakFill commented on src/containers/Chat/Chat.tsx
> +import { socketService } from '@/services/socketService';
done

2021-09-28 10:41 UTC, MakFill commented on src/models/MessageModel/MessageModel.ts
> +    this.roomId = message.roomId;
removed

2021-09-28 10:41 UTC, MakFill commented on src/models/MessageModel/MessageModel.ts
> +    this.name = message.name;
userName

2021-09-28 10:58 UTC, MakFill commented on src/pages/Game/Game.tsx
> +import { Chat } from '@/containers/Chat';
done

2021-09-28 11:01 UTC, MakFill commented on src/store/actions/addRoomState.ts
> +export const addRoomState = createAction<IRoomState>('addGameSettings');
renamed

2021-09-28 11:13 UTC, MakFill commented on src/containers/SendMessageForm/SendMessageForm.tsx
> +    const sendedMessage = new SendMessageModel({
ok

2021-09-28 11:15 UTC, MakFill commented on src/containers/SendMessageForm/SendMessageForm.tsx
> +      <input
They look different so no

2021-09-28 11:15 UTC, MakFill commented on src/helpers/getMessageByMessageFromBE.ts
> +import { MessageModel } from '@/models/MessageModel';
deleted helper

2021-09-28 11:17 UTC, MakFill commented on src/store/actions/messageActions.ts
> +  addMessage: createAction<IMessage>('addMessage'),
done

2021-09-28 11:19 UTC, MakFill commented on src/store/actions/roomMembersActions.ts
> +  addRoomMembers: createAction<IUser[]>('addRoomMembers'),
done

2021-09-28 11:38 UTC, MakFill commented on src/helpers/getMessagesByRoomId.ts
> +export function getMessagesByRoomId(roomId: string) {
done

2021-09-28 11:39 UTC, MakFill commented on src/containers/Chat/Chat.tsx
> +    dispatch<any>(getMessagesByRoomId(roomId));
cause I don't know what is the type should be there

2021-09-28 14:34 UTC, mrakofff requested changes

2021-09-28 14:34 UTC, mrakofff commented on src/containers/Chat/Chat.tsx
> +export const Chat = (): JSX.Element => {
use `React.FC` to describe Chat variable. It will infer returnType

2021-09-28 14:34 UTC, mrakofff commented on src/containers/Chat/Chat.tsx
> +import { SendMessageForm } from '@/containers/SendMessageForm';
reduce path

2021-09-28 14:34 UTC, mrakofff commented on src/containers/SendMessageForm/SendMessageForm.tsx
> +      <input
You could override pass your own className and rewrite styles. The idea was to use common components, but let it be

2021-09-28 14:34 UTC, mrakofff commented on src/store/selectors/messageSelectors.ts
> +  messageSelector: createSelector((state: RootState) => state.messages, (messages) => messages),
I think `selector`  postfix is redundant

2021-09-28 14:34 UTC, mrakofff commented on src/store/selectors/roomStateSelectors.ts
> +  roomTitle: createSelector((state: RootState) => state.roomState, (state) => state.roomTitle),
create local variable `rootStateSelector` that will be equal to `(state: RootState) => state.roomState` and you will be able to reuse in each selector

2021-09-28 14:34 UTC, mrakofff commented on src/store/actions/setRoomStateAction.ts
> +export const setRoomState = createAction<IRoomState>('[ROOM_STATE]:setRoomState');
export object `roomActions` with key as actions like `userActions`

2021-09-28 14:34 UTC, mrakofff commented on src/store/selectors/membersSelectors.ts
> +  members: createSelector((state: RootState) => state.members, (state) => state),
add `rootStateSelector`

2021-09-28 14:34 UTC, mrakofff commented on src/store/selectors/userSelectors.ts
> +  userId: createSelector((state: RootState) => state.user, (state) => state.userId),
add `rootStateSelector`

2021-09-28 14:34 UTC, mrakofff commented on src/store/actions/messageActions.ts
> +      const messagesFromBE: IMessageFromBE[] = await httpClient.http.get(`/api/messages?roomId=${roomId}`);
add `try/catch` like in example to increase stability 
doc: https://redux-toolkit.js.org/api/createAsyncThunk#handling-thunk-errors

2021-09-28 14:34 UTC, mrakofff commented on src/store/actions/membersActions.ts
> +  deleteRoomMember: createAction<string | number>('[MEMBERS]:deleteRoomMember'),
- find out the right type and update member model.
- use `IModel['field']` like type (`example`)

2021-09-28 14:34 UTC, mrakofff commented on src/pages/Game/Game.tsx
>  const title = 'Name room';
If you want you could update title from redux:)

2021-09-28 14:34 UTC, mrakofff commented on src/containers/SendMessageForm/SendMessageForm.module.scss
> +    width: fit-content;
No problem just a question

2021-09-28 14:42 UTC, MakFill commented on src/containers/Chat/Chat.tsx
> +export const Chat = (): JSX.Element => {
done

2021-09-28 14:42 UTC, MakFill commented on src/containers/Chat/Chat.tsx
> +import { SendMessageForm } from '@/containers/SendMessageForm';
done

2021-09-28 14:44 UTC, MakFill commented on src/store/selectors/messageSelectors.ts
> +  messageSelector: createSelector((state: RootState) => state.messages, (messages) => messages),
renamed

2021-09-28 14:46 UTC, MakFill commented on src/store/selectors/roomStateSelectors.ts
> +  roomTitle: createSelector((state: RootState) => state.roomState, (state) => state.roomTitle),
done

2021-09-28 14:48 UTC, MakFill commented on src/store/actions/setRoomStateAction.ts
> +export const setRoomState = createAction<IRoomState>('[ROOM_STATE]:setRoomState');
done

2021-09-28 14:49 UTC, mrakofff approved these changes

2021-09-28 14:52 UTC, MakFill commented on src/store/selectors/membersSelectors.ts
> +  members: createSelector((state: RootState) => state.members, (state) => state),
done

2021-09-28 14:53 UTC, MakFill commented on src/store/selectors/userSelectors.ts
> +  userId: createSelector((state: RootState) => state.user, (state) => state.userId),
done

2021-09-28 15:07 UTC, MakFill commented on src/pages/Game/Game.tsx
>  const title = 'Name room';
done

2021-09-28 15:18 UTC, MakFill commented on src/store/actions/membersActions.ts
> +  deleteRoomMember: createAction<string | number>('[MEMBERS]:deleteRoomMember'),
done

2021-09-29 10:54 UTC, andreikaptsiuh approved these changes

2021-09-29 12:23 UTC, merged