[PP-39] Add handlers for tasks actions
mrakofff/pointing-poker-fe pull request #27
Opened 2021-09-30 17:41 UTC by andreikaptsiuh

Task: https://andrei-lysiuk.atlassian.net/browse/PP-39
Description:
 - create tasks reducer
 - add actions to get all tasks after user join/create room
 - add handlers to catch all socket events related to tasks

2021-09-30 17:45 UTC, MakFill commented on src/components/Issues/Issues.tsx
> +import { taskActions } from '@/store/actions/taskActions';
Тут будет запись про alias, но я опережу

2021-09-30 17:47 UTC, MakFill commented on src/models/TaskModel/TaskModel.ts
> +  score: number;
скор string, в колодах не только числа

2021-09-30 17:47 UTC, MakFill commented on src/store/actions/taskActions.ts
> +import { TaskModel } from '@/models/TaskModel';
alias

2021-09-30 17:50 UTC, MakFill commented on src/store/store.ts
> +import { tasks } from './reducers/tasksReducer';
алиасы

2021-09-30 17:51 UTC, MakFill commented on src/utils/interfaces/ITask.ts
> +  score: number;
score string

2021-09-30 17:53 UTC, andreikaptsiuh commented on src/utils/interfaces/ITask.ts
> +  score: number;
fix

2021-09-30 17:53 UTC, andreikaptsiuh commented on src/models/TaskModel/TaskModel.ts
> +  score: number;
ok

2021-09-30 17:56 UTC, andreikaptsiuh commented on src/store/actions/taskActions.ts
> +import { TaskModel } from '@/models/TaskModel';
fix

2021-09-30 17:57 UTC, andreikaptsiuh commented on src/store/store.ts
> +import { tasks } from './reducers/tasksReducer';
fix

2021-09-30 18:00 UTC, andreikaptsiuh commented on src/components/Issues/Issues.tsx
> +import { taskActions } from '@/store/actions/taskActions';
исправил

2021-09-30 18:24 UTC, MakFill approved these changes

2021-09-30 18:48 UTC, mrakofff requested changes

2021-09-30 18:48 UTC, mrakofff commented on src/components/Issues/Issues.tsx
> +    socketService.on(SocketEvent.TaskDelete, updateTasks);
you should call different actions depends on event

2021-09-30 21:35 UTC, Praddby commented on src/components/Issues/Issues.tsx
> +  }, [roomId]);
Это работает? У нас же `roomId` постоянный.

2021-09-30 21:35 UTC, Praddby commented on src/components/Issues/Issues.tsx
> +    socketService.on(SocketEvent.TaskUpdateActive, updateTasks);
Если у нас обновление Тасок идет по `http`, зачем тогда БЕ возвращает чтото там? Может просто слать пустое событи?

2021-09-30 21:35 UTC, Praddby commented on src/store/reducers/tasksReducer.ts
> +      state.push(...action.payload);
При любых событиях с тасками, мы в `Issues.tsx` диспатчем все таски, полученные с БЕ. Не будет ли `push` их удваивать?

2021-09-30 21:35 UTC, Praddby commented on src/store/store.ts
> +  messages, user, roomState, members, tasks,
тут лучше уже в переносы после каждого reducers.

2021-10-01 13:32 UTC, andreikaptsiuh commented on src/components/Issues/Issues.tsx
> +  }, [roomId]);
По идее должно, мы ведь можем подключаться к разным комнатам

2021-10-01 13:35 UTC, andreikaptsiuh commented on src/store/store.ts
> +  messages, user, roomState, members, tasks,
ок

2021-10-01 13:46 UTC, andreikaptsiuh commented on src/store/reducers/tasksReducer.ts
> +      state.push(...action.payload);
Все таски мы будем получать только один раз, при подключении к комнате, так что удваиваться не должно

2021-10-01 21:04 UTC, andreikaptsiuh commented on src/components/Issues/Issues.tsx
> +    socketService.on(SocketEvent.TaskDelete, updateTasks);
fix

2021-10-01 21:15 UTC, mrakofff requested changes

2021-10-01 21:15 UTC, mrakofff commented on src/components/Issues/Issues.tsx
> +    dispatch(taskActions.getTasks(roomId));
you could get `roomId` inside `thunk` with `getState` and `useSelector`

2021-10-01 21:15 UTC, mrakofff commented on src/components/Issues/Issues.tsx
> +        <div>{task.title}</div>
what about task score

2021-10-01 21:15 UTC, mrakofff commented on src/components/Issues/Issues.tsx
> +    dispatch(taskActions.deleteTask(deletedTask));
do we need full task or we need only `id`?

2021-10-01 21:15 UTC, mrakofff commented on src/components/Issues/Issues.tsx
> +    dispatch(taskActions.updateTaskActive(updatedTask));
what about setting active by `id` and other tasks become inactive?

2021-10-01 21:22 UTC, andreikaptsiuh commented on src/components/Issues/Issues.tsx
> +    dispatch(taskActions.deleteTask(deletedTask));
fix

2021-10-01 21:24 UTC, andreikaptsiuh commented on src/components/Issues/Issues.tsx
> +    dispatch(taskActions.updateTaskActive(updatedTask));
fix

2021-10-01 21:25 UTC, andreikaptsiuh commented on src/components/Issues/Issues.tsx
> +        <div>{task.title}</div>
add

2021-10-01 21:42 UTC, andreikaptsiuh commented on src/components/Issues/Issues.tsx
> +    dispatch(taskActions.getTasks(roomId));
fix

2021-10-01 22:33 UTC, mrakofff approved these changes

2021-10-02 07:43 UTC, merged