[PP-49] Add handlers to create/delete/vote tasks
mrakofff/pointing-poker-fe pull request #29
Opened 2021-10-04 13:09 UTC by andreikaptsiuh

Task: https://andrei-lysiuk.atlassian.net/browse/PP-49
Description: 
- Add handlers to create/delete/vote tasks
![image](https://user-images.githubusercontent.com/76453952/135859083-c2e5959d-9cac-4e3f-81e0-bf71718f1e62.png)
![image](https://user-images.githubusercontent.com/76453952/135859116-ecda35a5-60fb-47ae-b0ff-dfb7f4161e44.png)

2021-10-04 13:23 UTC, mrakofff requested changes

2021-10-04 13:23 UTC, mrakofff commented on src/components/Task/Task.tsx
> +        <h5>{`PP-${task.id}`}</h5>
why `pp-` prefix?

2021-10-04 13:23 UTC, mrakofff commented on src/components/Task/Task.tsx
> +          onClick={removeTask}
should we add confirm to exclude random click?

2021-10-04 13:23 UTC, mrakofff commented on src/components/Task/Task.tsx
> +        <p>{task.score}</p>
Admin should be able to set task score after all users vote to save task score in db

2021-10-04 13:23 UTC, mrakofff commented on src/components/CreateTaskPanel/CreateTaskPanel.tsx
> +      taskEditorHandler();
you will get an error coz event is undefined inside handler : `const { value } = event.target;`

2021-10-04 13:25 UTC, andreikaptsiuh commented on src/components/Task/Task.tsx
> +        <h5>{`PP-${task.id}`}</h5>
fix

2021-10-04 13:30 UTC, andreikaptsiuh commented on src/components/CreateTaskPanel/CreateTaskPanel.tsx
> +      taskEditorHandler();
fixed

2021-10-04 16:06 UTC, andreikaptsiuh commented on src/components/Task/Task.tsx
> +          onClick={removeTask}
fix

2021-10-04 16:28 UTC, andreikaptsiuh commented on src/components/Task/Task.tsx
> +        <p>{task.score}</p>
fix

2021-10-04 16:40 UTC, mrakofff requested changes

2021-10-04 16:40 UTC, mrakofff commented on src/models/SendTaskModel/SendTaskModel.ts
> +interface task {
Should it be `INewTask`?

2021-10-04 16:43 UTC, andreikaptsiuh commented on src/models/SendTaskModel/SendTaskModel.ts
> +interface task {
ok

2021-10-04 17:13 UTC, mrakofff approved these changes

2021-10-04 17:13 UTC, mrakofff commented on src/components/Task/Task.tsx
> +    socketService.emit(SocketEvent.TaskUpdateScore, {
emit only if `task.score !== score`

2021-10-04 17:13 UTC, mrakofff commented on src/components/Task/Task.tsx
> +  const [score, setScore] = useState(task.score);
mote to the top of component

2021-10-04 17:17 UTC, andreikaptsiuh commented on src/components/Task/Task.tsx
> +  const [score, setScore] = useState(task.score);
fix

2021-10-04 17:17 UTC, andreikaptsiuh commented on src/components/Task/Task.tsx
> +    socketService.emit(SocketEvent.TaskUpdateScore, {
fix

2021-10-04 17:28 UTC, mrakofff approved these changes

2021-10-04 19:17 UTC, MakFill approved these changes

2021-10-04 21:30 UTC, mrakofff requested changes

2021-10-04 21:30 UTC, mrakofff commented on src/store/actions/taskActions.ts
> +  deleteTask: createAction<number>('[TASKS]:deleteTask'),
any reason for update?

2021-10-04 21:30 UTC, mrakofff commented on src/store/actions/taskActions.ts
> +          .sort((taskOne, taskTwo) => taskOne.id - taskTwo.id);
should we sort by task date or even sort or it should be done by `BE`?

2021-10-04 21:30 UTC, mrakofff commented on src/components/Task/Task.tsx
> +  const defaultScore = task.score === '0' ? '?' : task.score;
perhaps you should not set `0` in model and leave `null` if you do this check. Also move it to `useState` callback https://ru.reactjs.org/docs/hooks-reference.html#lazy-initial-state

2021-10-04 21:30 UTC, mrakofff commented on src/components/Task/Task.tsx
> +        [styles.task__active]: task.isActive === true,
could be simplified with `[styles.task__active]: task.isActive`

2021-10-04 21:30 UTC, mrakofff commented on src/components/Issues/Issues.tsx
> +  const deleteTaskHandler = (id: number) => {
use type from Task interface

2021-10-04 21:31 UTC, andreikaptsiuh commented on src/components/Task/Task.tsx
> +        [styles.task__active]: task.isActive === true,
fix

2021-10-04 21:37 UTC, andreikaptsiuh commented on src/components/Task/Task.tsx
> +  const defaultScore = task.score === '0' ? '?' : task.score;
fix

2021-10-05 05:08 UTC, MakFill commented on src/store/actions/taskActions.ts
> +          .sort((taskOne, taskTwo) => taskOne.id - taskTwo.id);
we should sort by id - it's similar like sort by date

2021-10-05 05:09 UTC, MakFill commented on src/components/Issues/Issues.tsx
> +  const deleteTaskHandler = (id: number) => {
refactored

2021-10-05 05:18 UTC, MakFill commented on src/store/actions/taskActions.ts
> +  deleteTask: createAction<number>('[TASKS]:deleteTask'),
refactored

2021-10-06 20:49 UTC, merged