[PP-48] Check user vote through the game progress
mrakofff/pointing-poker-fe pull request #31
Opened 2021-10-05 15:05 UTC by MakFill

Task: https://andrei-lysiuk.atlassian.net/browse/PP-48
Integration vote system with BE

2021-10-05 18:01 UTC, mrakofff requested changes

2021-10-05 18:01 UTC, mrakofff commented on src/components/CommonArea/CardNest/CardNest.tsx
> +      {userRole !== 'spectator'
do user still have role if he is spectator?

2021-10-05 18:01 UTC, mrakofff commented on src/components/CommonArea/Table/Table.tsx
> +      socketService.emit(SocketEvent.RoomShow, { id: activeTask.id });
why payload is object but not a string?

2021-10-05 18:01 UTC, mrakofff commented on src/components/Controls/Controls.tsx
> +               [styles.disable]: !activeTask,
you could add styles for `:disabled` pseudo-class

2021-10-05 18:01 UTC, mrakofff commented on src/store/reducers/roomStateReducer.ts
> +  roomState: StateRoomTitle.reset.toString(),
why `.toString`?

2021-10-05 18:01 UTC, mrakofff commented on src/store/actions/roomStateAction.ts
> +  dealerRights?: string;
do we use this field?

2021-10-05 18:01 UTC, mrakofff commented on src/containers/SendMessageForm/SendMessageForm.tsx
> +        className={classNames(styles.submit, {
why don't use `disabled` props?

2021-10-05 18:01 UTC, mrakofff commented on src/components/User/User.tsx
> +        score={user.score || ''}
you could destcruture from `user` on 12 row, and set default value in `CardNest`

2021-10-05 18:01 UTC, mrakofff commented on src/components/Task/Task.tsx
> +            [styles.vote_btn__disabled]: task.isActive || role !== 'admin',
`disabled` prop?

2021-10-05 18:01 UTC, mrakofff commented on src/components/Task/Task.tsx
> +  const role = useSelector(userSelectors.role)?.role;
`role.role`?

2021-10-05 18:01 UTC, mrakofff commented on src/components/CommonArea/Table/Table.tsx
> +          && <SecondaryButton onClick={() => gameFinish()}>Reset</SecondaryButton>
remove redundant arrow function and use as callback

2021-10-05 18:01 UTC, mrakofff commented on src/store/selectors/userSelectors.ts
> +    (state) => state.members.find((member) => member.userId === state.user.userId)),
- why don't you store userRole in userReducer?
- why `roleSelector` returns `IUser` but not `IUser['role']`

2021-10-06 07:00 UTC, MakFill commented on src/components/CommonArea/Table/Table.tsx
> +      socketService.emit(SocketEvent.RoomShow, { id: activeTask.id });
refactored

2021-10-06 08:06 UTC, MakFill commented on src/components/Controls/Controls.tsx
> +               [styles.disable]: !activeTask,
refactored

2021-10-06 08:57 UTC, MakFill commented on src/store/reducers/roomStateReducer.ts
> +  roomState: StateRoomTitle.reset.toString(),
fixed

2021-10-06 08:57 UTC, MakFill commented on src/store/actions/roomStateAction.ts
> +  dealerRights?: string;
no, removed

2021-10-06 09:02 UTC, MakFill commented on src/containers/SendMessageForm/SendMessageForm.tsx
> +        className={classNames(styles.submit, {
refactored

2021-10-06 09:04 UTC, MakFill commented on src/components/User/User.tsx
> +        score={user.score || ''}
refactored

2021-10-06 09:05 UTC, MakFill commented on src/components/Task/Task.tsx
> +            [styles.vote_btn__disabled]: task.isActive || role !== 'admin',
refactored

2021-10-06 09:07 UTC, MakFill commented on src/components/CommonArea/Table/Table.tsx
> +          && <SecondaryButton onClick={() => gameFinish()}>Reset</SecondaryButton>
refactored

2021-10-06 09:17 UTC, andreikaptsiuh approved these changes

2021-10-06 09:18 UTC, MakFill commented on src/components/Task/Task.tsx
> +  const role = useSelector(userSelectors.role)?.role;
fixed

2021-10-06 09:19 UTC, MakFill commented on src/store/selectors/userSelectors.ts
> +    (state) => state.members.find((member) => member.userId === state.user.userId)),
refactored

2021-10-06 09:21 UTC, MakFill commented on src/components/CommonArea/CardNest/CardNest.tsx
> +      {userRole !== 'spectator'
removed as outdated

2021-10-06 15:17 UTC, mrakofff requested changes

2021-10-06 15:17 UTC, mrakofff commented on src/components/Controls/Controls.tsx
> +     && (
add condition before return like if(!role) {return null }

2021-10-06 15:17 UTC, mrakofff commented on src/containers/SendMessageForm/SendMessageForm.tsx
> +        disabled={text.trim().length === 0}
`!text.trim().length`

2021-10-06 15:17 UTC, mrakofff commented on src/store/reducers/roomStateReducer.ts
> +      ...state, roomTitle: action.payload.title, roomId: action.payload.id, roomState: action.payload.state,
you could mutate and destructure action

2021-10-06 15:17 UTC, mrakofff commented on src/components/Button/Button.module.scss
> +    background-color: $shadow-grey
you could join with previous selector with `,`

2021-10-06 15:17 UTC, mrakofff commented on src/components/CreateTaskPanel/CreateTaskPanel.tsx
> +              [styles.taskEditor__btn_close]: isTaskEditorOpen === true,
`[styles.taskEditor__btn_close]: isTaskEditorOpen`

2021-10-06 15:17 UTC, mrakofff commented on src/components/InviteBtn/InviteBtn.tsx
> +  const url = window.location.href;
could you use `useLocation` hook?

2021-10-06 20:49 UTC, merged