[PP-8] Add single service to make requests to be
mrakofff/pointing-poker-fe pull request #5
Opened 2021-09-04 19:49 UTC by andreikaptsiuh

Task: https://andrei-lysiuk.atlassian.net/browse/PP-8
Description: Create class that will make requests to BE via axios lib

2021-09-05 09:54 UTC, mrakofff requested changes
Resolve conflicts with `develop`

2021-09-05 09:55 UTC, mrakofff commented on src/api/axios.ts
> +import { ICard, IRoom, ITask, IUser } from '@/interfaces';
👍

2021-09-05 10:55 UTC, mrakofff requested changes
1. Add comments with naming, additional code. 
1. Good point with interface folder 👍 
1. Add basic `tests`

2021-09-05 10:55 UTC, mrakofff commented on src/api/axios.ts
> +	readonly instance: AxiosInstance;
Should it be `private`?

2021-09-05 10:55 UTC, mrakofff commented on src/api/axios.ts
> +  constructor(baseURL: string){
Could be `private` as well. BaseURL should be `optional` coz we will have separate class for BE links

2021-09-05 10:55 UTC, mrakofff commented on src/api/axios.ts
> +export class Axios {
It's better to set it like `Http` and `this.instance` it should be an instance of this class, but not an instance of `axios`. It's better to use `_method` to show that `method/variable` is private. So you could have `_instance: Http` and `_http: AxiosInstance` fields.

2021-09-05 10:55 UTC, mrakofff commented on src/interfaces.ts
> +  id?: number;
All `ids` most of the time will be a `string` type

2021-09-05 10:55 UTC, mrakofff commented on src/api/axios.ts
> +  getTaskById = (id: number) => this.instance.get<ITask>(`/tasks/${id}`);
use generic type of `ITask`

2021-09-05 10:55 UTC, mrakofff commented on src/api/axios.ts
> +  protected _handleError = (error: AxiosError) => {
why it'is `protected`?

2021-09-05 10:55 UTC, mrakofff commented on src/api/axios.ts
> +    if (error.response) {
I think it's redundant and you could log only `Error` object, if you need you could print it through the `console.dir`

2021-09-05 10:55 UTC, mrakofff commented on src/api/axios.ts
> +  deleteTask = (id: number) => this.instance.delete(`/tasks/${id}`);
I think it's out of scope of this task. Also BE requests will be in a separate `class`

2021-09-05 14:24 UTC, andreikaptsiuh commented on src/api/axios.ts
> +	readonly instance: AxiosInstance;
fixed

2021-09-05 14:30 UTC, andreikaptsiuh commented on src/api/axios.ts
> +  constructor(baseURL: string){
How i can make it? I not should add create instance?

2021-09-05 14:31 UTC, andreikaptsiuh commented on src/api/axios.ts
> +  deleteTask = (id: number) => this.instance.delete(`/tasks/${id}`);
deleted

2021-09-05 14:32 UTC, andreikaptsiuh commented on src/api/axios.ts
> +export class Axios {
complete

2021-09-05 14:32 UTC, andreikaptsiuh commented on src/api/axios.ts
> +  protected _handleError = (error: AxiosError) => {
fixed

2021-09-05 14:34 UTC, andreikaptsiuh commented on src/interfaces.ts
> +  id?: number;
fixed

2021-09-05 14:55 UTC, mrakofff commented on src/api/axios.ts
> +  constructor(baseURL: string){
https://metanit.com/web/typescript/3.4.php

2021-09-06 17:14 UTC, mrakofff requested changes
Did you test it? does it works? coz i have some doubts with `static _instance`. If it does so good job 👍 
Do not forget to create some basic tests

2021-09-06 17:14 UTC, mrakofff commented on src/api/HttpClient.ts
> +	private instance!: AxiosInstance;
rename to `_http` || `_httpClient` and why do you need `!` symbol?

2021-09-06 17:14 UTC, mrakofff commented on src/api/HttpClient.ts
> +	static classInstance?: HTTPClient;
rename to `_instance` and why it's `optional`?

2021-09-06 18:28 UTC, andreikaptsiuh commented on src/api/HttpClient.ts
> +	private instance!: AxiosInstance;
fix

2021-09-07 08:38 UTC, mrakofff requested changes
I hope it's latest update request:)

2021-09-07 08:38 UTC, mrakofff commented on src/api/HttpClient.ts
> +	}
Is it problem with `github` or it's problem with formatting?

2021-09-07 08:38 UTC, mrakofff commented on src/api/HttpClient.ts
> +  constructor(public baseURL = ' ') {
is it empty string or it's space ` `?

2021-09-07 08:38 UTC, mrakofff commented on src/api/HttpClient.ts
> +	private _axios!: AxiosInstance;
Why do you need this `!` ?) Any reason? As I remember it's a sign to exclude optionality?

2021-09-07 08:38 UTC, mrakofff commented on src/api/HttpClient.ts
> +  private _initializeResponseInterceptor = () => {
Perhaps it's better to set `_initializeInterceptors` coz we will insert request interceptor too.

2021-09-07 08:38 UTC, mrakofff commented on src/api/HttpClient.ts
> +  static getClassInstance(){
Could we reduce name to `getInstance` coz we have any additional instances?

2021-09-07 10:58 UTC, andreikaptsiuh commented on src/api/HttpClient.ts
> +  constructor(public baseURL = ' ') {
it's space

2021-09-07 12:09 UTC, andreikaptsiuh commented on src/api/HttpClient.ts
> +	}
It's problem with gitHub

2021-09-07 12:16 UTC, andreikaptsiuh commented on src/api/HttpClient.ts
> +  static getClassInstance(){
fix

2021-09-07 12:17 UTC, andreikaptsiuh commented on src/api/HttpClient.ts
> +  private _initializeResponseInterceptor = () => {
add request interceptor

2021-09-07 12:18 UTC, andreikaptsiuh commented on src/api/HttpClient.ts
> +	private _axios!: AxiosInstance;
fix

2021-09-07 15:39 UTC, mrakofff requested changes
And final corrections:)

2021-09-07 15:39 UTC, mrakofff commented on src/api/HttpClient.ts
> +  constructor(public baseURL = ' ') {
any reason for empty space? we could have problems with empty space in requests `url`

2021-09-07 15:39 UTC, mrakofff commented on src/api/HttpClient.ts
> +    this._initializeInterceptor();
`_initializeInterceptor` => `_initializeInterceptors`

2021-09-07 15:39 UTC, mrakofff commented on src/api/HttpClient.ts
> +  constructor(public baseURL = ' ') {
could we make constructor `private` to exclude handle creation entities?

2021-09-07 19:00 UTC, andreikaptsiuh commented on src/api/HttpClient.ts
> +    this._initializeInterceptor();
fix

2021-09-07 19:02 UTC, andreikaptsiuh commented on src/api/HttpClient.ts
> +  constructor(public baseURL = ' ') {
fix

2021-09-08 06:27 UTC, Praddby approved these changes

2021-09-08 09:05 UTC, mrakofff requested changes

2021-09-08 09:05 UTC, mrakofff commented on src/api/HttpClient.ts
> +  constructor(private baseURL = '') {
update with `private constructor`

2021-09-08 09:05 UTC, mrakofff commented on src/api/HttpClient.ts
> +export class _HTTPClient {
remove `_` from class name

2021-09-08 09:05 UTC, mrakofff commented on src/test/HttpClient.test.ts
> +describe('Response', () => {
You don't need this test, add test for `baseUrl`. I think it will be enough

2021-09-08 09:05 UTC, mrakofff commented on src/api/HttpClient.ts
> +
Add please import of `http` or `httpClient` variable that will be equal to `HttpClient.getInstance().http`

2021-09-08 09:05 UTC, mrakofff commented on src/api/HttpClient.ts
> +};
Please add `http` getter that will return `this._axios`

2021-09-08 09:16 UTC, andreikaptsiuh commented on src/api/HttpClient.ts
> +export class _HTTPClient {
fix

2021-09-08 09:24 UTC, andreikaptsiuh commented on src/api/HttpClient.ts
> +export class _HTTPClient {
fix

2021-09-08 09:24 UTC, andreikaptsiuh commented on src/api/HttpClient.ts
> +
add

2021-09-08 09:24 UTC, andreikaptsiuh commented on src/api/HttpClient.ts
> +};
complete

2021-09-08 09:34 UTC, andreikaptsiuh commented on src/test/HttpClient.test.ts
> +describe('Response', () => {
fix

2021-09-08 10:00 UTC, mrakofff requested changes

2021-09-08 10:00 UTC, mrakofff commented on src/api/HttpClient.ts
> +};
it should not be an `axios` name. should be some abstract. 
About `getters` https://www.typescripttutorial.net/typescript-tutorial/typescript-getters-setters/

2021-09-08 10:00 UTC, mrakofff commented on src/test/HttpClient.test.ts
> +    axios.defaults.baseURL = url;
we should prevent overriding private `HttpClient` fields

2021-09-08 10:00 UTC, mrakofff commented on src/api/HttpClient.ts
> +	_axios: AxiosInstance;
make it private. we should hide request realization from outside

2021-09-08 10:00 UTC, mrakofff commented on src/test/HttpClient.test.ts
> +  test('Should return clean string', () => {
You should test that call requester will be with correct arguments, and passing baseUrl to constructor will affect any request after

2021-09-08 15:29 UTC, andreikaptsiuh commented on src/test/HttpClient.test.ts
> +describe('Response', () => {
fix

2021-09-08 15:31 UTC, andreikaptsiuh commented on src/api/HttpClient.ts
> +  constructor(private baseURL = '') {
update

2021-09-08 15:32 UTC, andreikaptsiuh commented on src/api/HttpClient.ts
> +	_axios: AxiosInstance;
fix

2021-09-09 06:51 UTC, andreikaptsiuh commented on src/test/HttpClient.test.ts
> +  test('Should return clean string', () => {
fix

2021-09-10 19:19 UTC, mrakofff approved these changes

2021-09-10 19:21 UTC, merged