[PP-7] Add basic game page
mrakofff/pointing-poker-fe pull request #7
Opened 2021-09-06 11:05 UTC by Praddby

Task: https://andrei-lysiuk.atlassian.net/browse/PP-7
Description: Add basic game page

2021-09-06 12:54 UTC, MakFill reviewed
Change imports in some files and rename folder Botton

2021-09-06 12:54 UTC, MakFill commented on src/components/Botton/Button.tsx
> +import styles from "./Button.module.scss";
Переименуй папку на Button

2021-09-06 12:54 UTC, MakFill commented on src/components/Botton/Button.module.scss
> +@import "../../variables.scss";
поменяй импорт на @/ вместо ../../

2021-09-06 17:04 UTC, mrakofff requested changes

2021-09-06 17:04 UTC, mrakofff commented on src/components/Botton/Button.module.scss
> +    box-shadow: inset 0 0 1.5rem #2B3A67;
What is this unknown color?

2021-09-06 17:04 UTC, mrakofff commented on src/components/Botton/Button.tsx
> +    <button type={type} className={`${styles.btn} ${btnStyle}`} onClick={callback}>
use `classnames` lib to merge 1+ classNames

2021-09-06 17:04 UTC, mrakofff commented on src/components/Botton/Button.tsx
> +  myStyles?: "btn-primary" | "btn-secondary";
you could add `className` prop to control button's styling from outside and exclude any conditions inside this component

2021-09-06 17:04 UTC, mrakofff commented on src/components/User/PanelUsers.tsx
> +  const listUsers: UserType[] = [
move it to separate file(like `mockUsers.js/json`) and you don't need function to create mocks

2021-09-06 17:04 UTC, mrakofff commented on src/components/User/User.module.scss
> +  margin-bottom: 1rem;
not correction but only note: you could add condition like: `not(:last-child)` with `margin` rule

2021-09-06 17:04 UTC, mrakofff commented on src/App.tsx
> +import GamePage from './pages/GamePage';
use `@/` alias

2021-09-06 17:04 UTC, mrakofff commented on src/components/Botton/Button.module.scss
> +  vertical-align: middle;
does it works for `inline-block` ?

2021-09-06 17:04 UTC, mrakofff commented on src/components/Botton/Button.module.scss
> +  background-color: transparent;
could be `background` only

2021-09-06 17:04 UTC, mrakofff commented on src/components/Botton/Button.module.scss
> +  transition: color 0.15s ease-in-out, background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
could be applied to `all` properties coz animation rules are the same

2021-09-06 17:04 UTC, mrakofff commented on src/components/Botton/Button.module.scss
> +  border-color: #2B3A67;
random colors?

2021-09-06 17:04 UTC, mrakofff commented on src/components/User/PanelUsers.tsx
> +      {listUsers.map((user: UserType) => <User user={user} key={user.id} />)}
U don't need to add types everywhere, TS is clever and understand that `listUsers` has `UserType[]` type and will infer single item type

2021-09-06 17:04 UTC, mrakofff commented on src/components/User/User.module.scss
> +  background-position: center;
could it be 1 property `background`?

2021-09-06 17:04 UTC, mrakofff commented on src/components/User/User.module.scss
> +  background-position: center;
the same question as before

2021-09-06 17:04 UTC, mrakofff commented on src/components/User/User.module.scss
> +  width: 2rem;
*if it should be a `square` so create internal(inside selector) variable and use it twice

2021-09-06 17:04 UTC, mrakofff commented on src/components/User/User.tsx
> +  const { name, surname, job, avatar, currentScore, type } = user;
Why do you decompose it? Just a question.

2021-09-06 17:04 UTC, mrakofff commented on src/components/User/User.tsx
> +      <div className={styles.score}>{currentScore ? currentScore : defaultScore}</div>
Could create some `scoreAnalizer` pure helper to make it outside the component

2021-09-06 17:04 UTC, mrakofff commented on src/components/VoteCard/PanelVoteCards.tsx
> +  const listCards: CardType[] = [
The same as `mockUsers`

2021-09-06 17:04 UTC, mrakofff commented on src/components/VoteCard/VoteCard.module.scss
> +  box-shadow: 1px 1px 2px 1px #999;
magic color?

2021-09-06 17:04 UTC, mrakofff commented on src/pages/GamePage.tsx
> +import { Button } from "@/components/Botton/Button";
add `index` file and reexport `Button` component to reduce import path. And check component folder name

2021-09-06 17:04 UTC, mrakofff commented on src/pages/GamePage.tsx
> +          <Button name="run round" myStyles="btn-primary" type="button" callback={handlerRun} />
default button type is `button` so do you need to pass it again?

2021-09-06 17:04 UTC, mrakofff commented on src/untils/types/index.ts
> +export type CardType = {
each type could be in separate file

2021-09-07 06:26 UTC, Praddby commented on src/components/Botton/Button.tsx
> +import styles from "./Button.module.scss";
Ok

2021-09-07 06:30 UTC, Praddby commented on src/components/Botton/Button.module.scss
> +@import "../../variables.scss";
Проверял доступность файла по пути через Ctrl + ЛКМ, а через @/ выдавало ошибку. Но в итоге рабтает оО.
Поправил.

2021-09-07 06:33 UTC, Praddby commented on src/components/Botton/Button.module.scss
> +    box-shadow: inset 0 0 1.5rem #2B3A67;
fix

2021-09-07 06:57 UTC, Praddby commented on src/components/User/PanelUsers.tsx
> +  const listUsers: UserType[] = [
Fix

2021-09-07 07:01 UTC, Praddby commented on src/components/User/User.module.scss
> +  margin-bottom: 1rem;
Ok

2021-09-07 07:06 UTC, Praddby commented on src/components/VoteCard/PanelVoteCards.tsx
> +  const listCards: CardType[] = [
fix

2021-09-07 07:09 UTC, Praddby commented on src/components/VoteCard/VoteCard.module.scss
> +  box-shadow: 1px 1px 2px 1px #999;
Added variables for color

2021-09-07 07:10 UTC, Praddby commented on src/pages/GamePage.tsx
> +import { Button } from "@/components/Botton/Button";
Ok

2021-09-07 07:11 UTC, Praddby commented on src/pages/GamePage.tsx
> +          <Button name="run round" myStyles="btn-primary" type="button" callback={handlerRun} />
Yes, you right.
remove type.

2021-09-07 07:15 UTC, Praddby commented on src/untils/types/index.ts
> +export type CardType = {
created separate files

2021-09-07 07:41 UTC, Praddby commented on src/components/Botton/Button.tsx
> +    <button type={type} className={`${styles.btn} ${btnStyle}`} onClick={callback}>
add lib classnames

2021-09-07 07:42 UTC, Praddby commented on src/components/Botton/Button.tsx
> +  myStyles?: "btn-primary" | "btn-secondary";
changed using lib classnames

2021-09-07 08:23 UTC, mrakofff commented on src/components/Botton/Button.module.scss
> +@import "../../variables.scss";
Выдавало какую ошибку?

2021-09-07 08:44 UTC, Praddby commented on src/components/Botton/Button.module.scss
> +@import "../../variables.scss";
При клике через контрл, должно переходить в файл, через @ он его не видели, путь не правильный.
Но при проверке в браузере, все норм.

2021-09-07 13:36 UTC, MakFill approved these changes

2021-09-07 13:37 UTC, mrakofff requested changes

2021-09-07 13:37 UTC, mrakofff commented on src/components/Button/index.tsx
> +import React, { FC } from "react";
Index file should only reexport variables. It shouldn't include code in this case

2021-09-07 13:37 UTC, mrakofff commented on src/components/Button/index.tsx
> +import classNames from "classnames/bind";
import could be simplified with `classnames`

2021-09-07 13:37 UTC, mrakofff commented on src/components/User/User.module.scss
> +  box-shadow: 0 1px 1px #666;
magic color

2021-09-07 13:37 UTC, mrakofff commented on src/store/users.json
> +  "users": [
Why did you wrap data with additional `users` key? I think it's redundant. It's not a JS object and it has name `users.json` so we don't need any nesting

2021-09-07 13:37 UTC, mrakofff commented on src/components/Button/index.tsx
> +  const className = cx({
create additional components that will pass additional `className` like `PrimaryButton` and `SecondaryButton`. Do not make simple button component so smart because It's redundant. And use `classnames` in more simple way(`className` - it's a prop from for `Button` component): 
`<button type={type} className={classNames(styles.btn, className)} onClick={onClick}>`

2021-09-07 13:37 UTC, mrakofff commented on src/components/Button/Button.module.scss
> +  vertical-align: middle;
Skipped question: does it work  for `display: inline-block;`?

2021-09-07 13:37 UTC, mrakofff commented on src/components/Button/Button.module.scss
> +  transition: color 0.15s ease-in-out, background-color 0.15s ease-in-out,
Skipped correction: replace with `transition: all 0.15s ease-in-out;`

2021-09-07 13:37 UTC, mrakofff commented on src/components/Button/index.tsx
> +  callback: () => void;
Skipped correction: replace with `onClick`

2021-09-07 13:37 UTC, mrakofff commented on src/components/Button/index.tsx
> +  name: string;
replace with `children` prop coz we could pass any `React` type

2021-09-07 13:39 UTC, mrakofff commented on src/components/Botton/Button.module.scss
> +@import "../../variables.scss";
Проверь настройки редактора

2021-09-07 15:22 UTC, Praddby commented on src/App.tsx
> +import GamePage from './pages/GamePage';
Ok

2021-09-07 15:22 UTC, Praddby commented on src/components/User/PanelUsers.tsx
> +      {listUsers.map((user: UserType) => <User user={user} key={user.id} />)}
Yes, you right. But it's more for developers to see what's coming.

2021-09-07 15:22 UTC, Praddby commented on src/components/User/User.module.scss
> +  background-position: center;
Yes, but not background-size: cover;

2021-09-07 15:22 UTC, Praddby commented on src/components/User/User.module.scss
> +  background-position: center;
Yes, you right.
Changed

2021-09-07 15:22 UTC, Praddby commented on src/components/User/User.module.scss
> +  width: 2rem;
Ok

2021-09-07 15:22 UTC, Praddby commented on src/components/User/User.tsx
> +  const { name, surname, job, avatar, currentScore, type } = user;
For use name: {name} or {job}. Not: {user.name} ot {user.job}.
Short entry

2021-09-07 15:30 UTC, Praddby commented on src/components/Button/index.tsx
> +import classNames from "classnames/bind";
without import "classnames/bind" don't  works bind styles. 
![image](https://user-images.githubusercontent.com/10601569/132371703-11f9a3c2-b13b-420a-8115-320d69972dd7.png)

2021-09-07 15:31 UTC, Praddby commented on src/components/Button/index.tsx
> +import classNames from "classnames/bind";
with bind!
![image](https://user-images.githubusercontent.com/10601569/132371924-5da9d08a-c9c1-4e8a-bd09-4ff3d4bee5fb.png)

2021-09-07 15:33 UTC, Praddby commented on src/components/User/User.module.scss
> +  box-shadow: 0 1px 1px #666;
Oh... fix)

2021-09-07 15:36 UTC, Praddby commented on src/store/users.json
> +  "users": [
I don't know (
You right.
fix

2021-09-07 15:42 UTC, Praddby commented on src/components/Button/Button.module.scss
> +  vertical-align: middle;
yes. https://developer.mozilla.org/ru/docs/Web/CSS/vertical-align
but this is not necessary ))

2021-09-07 15:44 UTC, Praddby commented on src/components/Button/Button.module.scss
> +  transition: color 0.15s ease-in-out, background-color 0.15s ease-in-out,
Ok

2021-09-07 15:45 UTC, Praddby commented on src/components/Button/index.tsx
> +  callback: () => void;
Ok

2021-09-07 16:27 UTC, Praddby commented on src/components/Button/index.tsx
> +import React, { FC } from "react";
Ok

2021-09-07 19:38 UTC, Praddby commented on src/components/Button/index.tsx
> +import classNames from "classnames/bind";
change it

2021-09-07 19:39 UTC, Praddby commented on src/components/Button/index.tsx
> +  const className = cx({
refactor

2021-09-07 19:39 UTC, Praddby commented on src/components/Button/index.tsx
> +  name: string;
refactor

2021-09-07 20:13 UTC, andreikaptsiuh approved these changes

2021-09-08 15:44 UTC, mrakofff requested changes
minor changes

2021-09-08 15:44 UTC, mrakofff commented on src/components/User/PanelUsers.tsx
> +      {listUsers.map((user: UserType) => <User user={user} key={user.id} />)}
You could hover and TS will show you the hint:) the same as for keys of object

2021-09-08 15:44 UTC, mrakofff commented on src/components/User/User.tsx
> +  const { name, surname, job, avatar, currentScore, type } = user;
You create additional constants for 1time using, is it necessary?)

2021-09-08 15:44 UTC, mrakofff commented on src/components/VoteCard/VoteCard.module.scss
> +    content: url(../../assets/images/checked.svg);
Could we use alias here or not? coz if we move this file we could have and error, am I right?

2021-09-08 15:44 UTC, mrakofff commented on src/components/User/User.module.scss
> +  background: url(../../assets/images/kick.svg) center no-repeat;
the same question for `url`

2021-09-08 15:44 UTC, mrakofff commented on src/App.tsx
> +import styles from '@/App.module.scss';
relative import

2021-09-08 19:37 UTC, Praddby commented on src/App.tsx
> +import styles from '@/App.module.scss';
ok

2021-09-08 19:42 UTC, Praddby commented on src/components/User/PanelUsers.tsx
> +      {listUsers.map((user: UserType) => <User user={user} key={user.id} />)}
Ok

2021-09-08 19:42 UTC, Praddby commented on src/components/User/User.module.scss
> +  background: url(../../assets/images/kick.svg) center no-repeat;
fix

2021-09-08 19:45 UTC, Praddby commented on src/components/User/User.tsx
> +  const { name, surname, job, avatar, currentScore, type } = user;
removed

2021-09-08 19:46 UTC, Praddby commented on src/components/VoteCard/VoteCard.module.scss
> +    content: url(../../assets/images/checked.svg);
fix

2021-09-08 20:24 UTC, mrakofff requested changes
latest small fixies

2021-09-08 20:24 UTC, mrakofff commented on src/components/Button/Button.tsx
> +import classNames from "classnames/bind";
remove `/bind`

2021-09-08 20:24 UTC, mrakofff commented on src/components/User/User.tsx
> +    () => getAvatar(user.avatar || undefined),
it will be `undefined` anyway if it doesn't exist)

2021-09-08 20:24 UTC, mrakofff commented on src/styles/variables.scss
> +$shadow-grey: #999;
use full size color, I mean not shortcut

2021-09-08 20:24 UTC, mrakofff commented on src/untils/types/UserType.ts
> +  currentScore: number | null;
Will it be the same if it will be optional?

2021-09-08 21:11 UTC, Praddby commented on src/components/User/User.tsx
> +    () => getAvatar(user.avatar || undefined),
User.avatar = "".  Затирает значение по умолчанию, и нет дефолтных иконок пользователя.

2021-09-08 21:27 UTC, Praddby commented on src/components/Button/Button.tsx
> +import classNames from "classnames/bind";
delete

2021-09-08 21:27 UTC, Praddby commented on src/styles/variables.scss
> +$shadow-grey: #999;
ok

2021-09-08 21:28 UTC, Praddby commented on src/untils/types/UserType.ts
> +  currentScore: number | null;
no

2021-09-08 21:31 UTC, Praddby commented on src/components/User/User.tsx
> +    () => getAvatar(user.avatar || undefined),
Chage getAvatar

2021-09-08 21:37 UTC, Praddby commented on src/untils/types/UserType.ts
> +  currentScore: number | null;
Chenge to currentScore: number;

2021-09-08 22:23 UTC, mrakofff approved these changes

2021-09-09 04:59 UTC, merged