[PP-14] Add routing
mrakofff/pointing-poker-fe pull request #8
Opened 2021-09-09 15:44 UTC by andreikaptsiuh

Task: https://andrei-lysiuk.atlassian.net/browse/PP-14
Description:
 - NavMap class that have baseUrl and methods that returns paths to FE pages(if it nested add nesting to the method)
 - Implement routing into the app
 - Add rooms route

2021-09-09 18:28 UTC, Praddby requested changes

2021-09-09 18:28 UTC, Praddby commented on src/App.tsx
> +import { navMap } from './NavMap/NavMap';
Что бы не было таких импортов './NavMap/NavMap', можно создать index.ts, там делать реекспорт , а путь для импорта сократиться до './NavMap'

2021-09-09 18:38 UTC, andreikaptsiuh commented on src/App.tsx
> +import { navMap } from './NavMap/NavMap';
Добавил

2021-09-09 19:35 UTC, Praddby approved these changes

2021-09-10 19:48 UTC, mrakofff requested changes

2021-09-10 19:48 UTC, mrakofff commented on package.json
> +    "@types/react-router-dom": "^5.1.8",
move @types to `devDependencies`

2021-09-10 19:48 UTC, mrakofff commented on src/NavMap/NavMap.ts
> +  home = () => `${this.baseUrl}/`;
remove `/` at the end

2021-09-10 19:48 UTC, mrakofff commented on src/App.tsx
> +        <Route path={navMap.home()} />
Before implementation this pages add `Redirect` inside both of empty pages

2021-09-10 19:48 UTC, mrakofff commented on src/NavMap/NavMap.ts
> +class NavMap {
add test for this class: for `baseUrl` and each method

2021-09-10 19:56 UTC, andreikaptsiuh commented on package.json
> +    "@types/react-router-dom": "^5.1.8",
moved

2021-09-10 19:57 UTC, andreikaptsiuh commented on src/NavMap/NavMap.ts
> +  home = () => `${this.baseUrl}/`;
fix

2021-09-11 07:59 UTC, andreikaptsiuh commented on src/NavMap/NavMap.ts
> +class NavMap {
add test

2021-09-11 07:59 UTC, andreikaptsiuh commented on src/App.tsx
> +        <Route path={navMap.home()} />
added

2021-09-11 11:24 UTC, MakFill approved these changes

2021-09-11 11:24 UTC, MakFill commented on src/App.tsx
> +        <Route path={navMap.game()} component={Game} />
Добавь может заглушку 404 на страницу с любым другим урл

2021-09-11 17:28 UTC, mrakofff approved these changes

2021-09-11 18:42 UTC, andreikaptsiuh commented on src/App.tsx
> +        <Route path={navMap.game()} component={Game} />
А мы будем делать 404? В том как сейчас сделано - всё что не ведёт на страницы лобби, хоум и гейм - перенаправляется на хоум.

2021-09-13 05:35 UTC, merged