[PP-9] Create vote card and connected user components
mrakofff/pointing-poker-fe pull request #9
Opened 2021-09-09 17:25 UTC by MakFill

Task: https://andrei-lysiuk.atlassian.net/browse/PP-9

Created vote card with styles and basic game mechanic

2021-09-09 18:22 UTC, Praddby requested changes

2021-09-09 18:22 UTC, Praddby commented on src/components/CommonArea/CardNest/CardNest.tsx
> +interface ICardNest {
Нужно выбрать один стиль и ему придерживаться. 
interface or type?

2021-09-09 18:22 UTC, Praddby commented on src/components/CommonArea/CardNest/CardNest.tsx
> +      ${isCardVisible ? styles.showCard : ''}`
Если тернарный оператор не полный, можно писать так:
isCardVisibke && styles.showCard

Так же, посмотри в сторону либы `classnames`. Она уже есть в зависимостях

2021-09-09 18:22 UTC, Praddby commented on src/components/CommonArea/CardNest/CardNest.tsx
> +        <div className={`${styles.backSide} ${selectedCardValue ? styles.chosenCardBackground : ''}`}>
Тут тоже можно заменить тернарный на &&

2021-09-09 18:22 UTC, Praddby commented on src/components/CommonArea/Table/Table.tsx
> +          {'Show cards'}
Может лучше в константу вынести?

2021-09-09 18:22 UTC, Praddby commented on src/components/VoteCard/VoteCard.tsx
>  };
Может тут имелось ввиду React.CSSProperties?

2021-09-09 19:24 UTC, MakFill commented on src/components/CommonArea/CardNest/CardNest.tsx
> +interface ICardNest {
Это временные пропсы пока нету редакса. А вообще везде делают интерфейсы

2021-09-09 19:25 UTC, MakFill commented on src/components/CommonArea/Table/Table.tsx
> +          {'Show cards'}
Зачем?

2021-09-09 19:26 UTC, MakFill commented on src/components/VoteCard/VoteCard.tsx
>  };
Да, забыл исправить

2021-09-09 19:36 UTC, Praddby commented on src/components/CommonArea/CardNest/CardNest.tsx
> +interface ICardNest {
Ок, буду тоже придерживаться интерфейсов

2021-09-09 19:38 UTC, Praddby commented on src/components/CommonArea/Table/Table.tsx
> +          {'Show cards'}
Вроде как так принято, типа "магические строки" не по фен-шую
А ещё, что за синтаксис такой? { и '? Можно же просто строку вставить?

2021-09-09 19:46 UTC, MakFill commented on src/components/CommonArea/Table/Table.tsx
> +          {'Show cards'}
Планировалось что там что то будет, но осталась строка

2021-09-09 19:48 UTC, MakFill commented on src/components/CommonArea/Table/Table.tsx
> +          {'Show cards'}
Т.е. const SHOW_CARDS = 'Show cards' вместо этого по твоему не будет избыточным усложнением?

2021-09-09 20:58 UTC, Praddby commented on src/components/CommonArea/Table/Table.tsx
> +          {'Show cards'}
Дело не в заграмождении кода, а в удобстве поддержания. Вносить правки и рефакторить проще, когда ты сразу видишь все "зависимости", а не ищешь где в коде строку ..

По мне, это не так страшно, и я не сталкивался с такими проблемами, просто пишу, как общепринято .

2021-09-09 21:05 UTC, Praddby approved these changes

2021-09-10 19:42 UTC, mrakofff requested changes

2021-09-10 19:42 UTC, mrakofff commented on src/components/Button/Button.module.scss
>    font-weight: 700;
Add variable for this

2021-09-10 19:42 UTC, mrakofff commented on src/components/Button/Button.module.scss
> +  transition: all .09s linear;
what an interesting zipper time. will user see so fast animation?) Perhaps it could be 0.1?)

2021-09-10 19:42 UTC, mrakofff commented on src/components/Button/Button.module.scss
> +  letter-spacing: .02em;
use `px` in so small props

2021-09-10 19:42 UTC, mrakofff commented on src/components/CommonArea/CardNest/CardNest.module.scss
> +    background-size: 1.5rem 1.5rem;
could it be `1.5rem` only?

2021-09-10 19:42 UTC, mrakofff commented on src/components/CommonArea/CardNest/CardNest.tsx
> +    <section className={`
use `classnames` joining, will reduce all conditions

2021-09-10 19:42 UTC, mrakofff commented on src/components/CommonArea/CardNest/CardNest.tsx
> +        <div className={classNames(styles.backSide, selectedCardValue && styles.chosenCardBackground)}>
check doc how to escape `&&` in `classnames` lib using

2021-09-10 19:42 UTC, mrakofff commented on src/components/CommonArea/CommonArea.tsx
> +  {isCardOpened,
move `{` to the previous row

2021-09-10 19:42 UTC, mrakofff commented on src/styles/variables.scss
> +$card-active: linear-gradient(45deg,#3993ff 12%,transparent 0,transparent 88%,#3993ff 0), linear-gradient(135deg, transparent 37%,#1a7bf2 0,#1a7bf2 63%, transparent 0), linear-gradient(45deg
add `-color` postfix to understand that it's a color variable. Perhaps it should be like `card-gradient-color--active` if we have default color. It shouln't be active we we don't have unactive state:)

2021-09-10 19:42 UTC, mrakofff commented on src/pages/Game/Game.tsx
>    const title = 'Name room';
move outside of the component

2021-09-10 19:42 UTC, mrakofff commented on src/components/VoteCard/VoteCard.tsx
> +  {
move to the previous row

2021-09-10 19:42 UTC, mrakofff commented on src/components/VoteCard/VoteCard.tsx
> +  styleName: string
rename with `className`

2021-09-10 19:42 UTC, mrakofff commented on src/components/VoteCard/VoteCard.module.scss
> +  background-color: $second-color !important;
why it's `!important`??

2021-09-10 19:42 UTC, mrakofff commented on src/components/VoteCard/VoteCard.module.scss
> +    margin-top: -.5rem;
add `0` before `.5`

2021-09-10 19:42 UTC, mrakofff commented on src/components/VoteCard/PanelVoteCards.tsx
> +          {
use `classnames` instead of `&&`

2021-09-10 19:42 UTC, mrakofff commented on src/components/VoteCard/PanelVoteCards.tsx
> +          onCardClick={onCardClick}
could it be `onClick` or component has another click handlers?

2021-09-10 19:42 UTC, mrakofff commented on src/components/User/User.tsx
> +  // const score = useMemo(
remove commended code if it's redundant

2021-09-10 19:42 UTC, mrakofff commented on src/components/User/User.tsx
> +import { CardNest } from "../CommonArea/CardNest";
use `@`

2021-09-10 19:42 UTC, mrakofff commented on src/components/User/User.tsx
> +// import { scoreAnalizer } from "@/helpers/scoreAnalizer";
remove comments

2021-09-10 19:42 UTC, mrakofff commented on src/components/User/User.module.scss
> +  letter-spacing: .02em;
use `px`

2021-09-10 19:42 UTC, mrakofff commented on src/components/User/User.module.scss
> +  padding: 2rem 0 2rem 0;
could it be `2rem 0` ?

2021-09-10 19:42 UTC, mrakofff commented on src/components/Controls/Controls.module.scss
> +    border-radius: .8rem;
add `0` before `.`

2021-09-10 19:42 UTC, mrakofff commented on src/components/CommonArea/Table/Table.tsx
> +        <p className={selectedCardValue || isCardOpened ? styles.none : ''}>
use `classnames`

2021-09-10 19:42 UTC, mrakofff commented on src/components/CommonArea/Table/Table.tsx
> +          className={selectedCardValue && !isCardOpened ? '' : styles.none}
`classnames`

2021-09-11 09:38 UTC, MakFill commented on src/components/Button/Button.module.scss
> +  transition: all .09s linear;
deleted

2021-09-11 09:38 UTC, MakFill commented on src/components/Button/Button.module.scss
> +  letter-spacing: .02em;
changed

2021-09-11 09:44 UTC, MakFill commented on src/components/CommonArea/CardNest/CardNest.module.scss
> +    background-size: 1.5rem 1.5rem;
Nope, if background-size: 1.5rem it would be different background

2021-09-11 09:46 UTC, MakFill commented on src/components/Button/Button.module.scss
>    font-weight: 700;
added

2021-09-11 10:02 UTC, MakFill commented on src/components/CommonArea/CardNest/CardNest.tsx
> +    <section className={`
added

2021-09-11 10:04 UTC, MakFill commented on src/components/CommonArea/CardNest/CardNest.tsx
> +        <div className={classNames(styles.backSide, selectedCardValue && styles.chosenCardBackground)}>
done

2021-09-11 10:16 UTC, MakFill commented on src/components/CommonArea/CommonArea.tsx
> +  {isCardOpened,
done

2021-09-11 10:18 UTC, MakFill commented on src/styles/variables.scss
> +$card-active: linear-gradient(45deg,#3993ff 12%,transparent 0,transparent 88%,#3993ff 0), linear-gradient(135deg, transparent 37%,#1a7bf2 0,#1a7bf2 63%, transparent 0), linear-gradient(45deg
changed

2021-09-11 10:19 UTC, MakFill commented on src/pages/Game/Game.tsx
>    const title = 'Name room';
done

2021-09-11 10:20 UTC, MakFill commented on src/components/VoteCard/VoteCard.tsx
> +  {
done

2021-09-11 10:21 UTC, MakFill commented on src/components/VoteCard/VoteCard.tsx
> +  styleName: string
done

2021-09-11 10:25 UTC, MakFill commented on src/components/VoteCard/VoteCard.module.scss
> +  background-color: $second-color !important;
coz it can't work without !important

2021-09-11 10:39 UTC, MakFill commented on src/components/VoteCard/PanelVoteCards.tsx
> +          {
done

2021-09-11 10:45 UTC, MakFill commented on src/components/VoteCard/PanelVoteCards.tsx
> +          onCardClick={onCardClick}
second. Replaced handler in component

2021-09-11 10:46 UTC, MakFill commented on src/components/User/User.tsx
> +  // const score = useMemo(
done

2021-09-11 10:46 UTC, MakFill commented on src/components/User/User.tsx
> +import { CardNest } from "../CommonArea/CardNest";
done

2021-09-11 10:47 UTC, MakFill commented on src/components/User/User.tsx
> +// import { scoreAnalizer } from "@/helpers/scoreAnalizer";
done

2021-09-11 10:48 UTC, MakFill commented on src/components/User/User.module.scss
> +  letter-spacing: .02em;
done

2021-09-11 10:48 UTC, MakFill commented on src/components/User/User.module.scss
> +  padding: 2rem 0 2rem 0;
yes

2021-09-11 10:49 UTC, MakFill commented on src/components/Controls/Controls.module.scss
> +    border-radius: .8rem;
done

2021-09-11 10:53 UTC, MakFill commented on src/components/CommonArea/Table/Table.tsx
> +        <p className={selectedCardValue || isCardOpened ? styles.none : ''}>
done

2021-09-11 10:54 UTC, MakFill commented on src/components/CommonArea/Table/Table.tsx
> +          className={selectedCardValue && !isCardOpened ? '' : styles.none}
done

2021-09-11 11:17 UTC, MakFill commented on src/components/VoteCard/VoteCard.module.scss
> +    margin-top: -.5rem;
done

2021-09-11 17:21 UTC, mrakofff requested changes

2021-09-11 17:21 UTC, mrakofff commented on src/components/Button/Button.module.scss
> +  border-radius: .8rem;
add `0` before `.`

2021-09-11 17:21 UTC, mrakofff commented on src/components/Button/Button.module.scss
> +    transition: 0.3s;
add animation type and properties

2021-09-11 17:21 UTC, mrakofff commented on src/components/CommonArea/CardNest/CardNest.module.scss
> +  border-radius: .6rem;
add `0`

2021-09-11 17:21 UTC, mrakofff commented on src/components/CommonArea/CardNest/CardNest.module.scss
> +  transition: 0.5s;
add transition details

2021-09-11 17:21 UTC, mrakofff commented on src/components/CommonArea/CardNest/CardNest.module.scss
> +    border-radius: .6rem;
`0`

2021-09-11 17:21 UTC, mrakofff commented on src/untils/types/UserType.ts
> +export interface UserType {
if it's interface move it to `interfaces` and rename to `IUser`

2021-09-11 17:21 UTC, mrakofff commented on src/styles/variables.scss
> +$card-bakside-chosen-color: linear-gradient(45deg,#3993ff 12%,transparent 0,transparent 88%,#3993ff 0), linear-gradient(135deg, transparent 37%,#1a7bf2 0,#1a7bf2 63%, transparent 0), linear-gradient(
typo in `back` word

2021-09-11 17:21 UTC, mrakofff commented on src/components/VoteCard/VoteCard.module.scss
> +  font-weight: 600;
move to scss `variables`

2021-09-11 17:21 UTC, mrakofff commented on src/components/VoteCard/VoteCard.module.scss
> +  transition: 0.3s;
add transition details

2021-09-11 17:21 UTC, mrakofff commented on src/components/VoteCard/PanelVoteCards.tsx
> +            {
Perhaps it will be better to create `className` variable with `useMemo`. It will be more readable.

2021-09-11 17:21 UTC, mrakofff commented on src/components/CommonArea/CardNest/CardNest.tsx
> +  cardStyle?: string;
replace with `className`

2021-09-11 17:21 UTC, mrakofff commented on src/components/CommonArea/Table/Table.tsx
> +          [styles.none]: selectedCardValue || isCardOpened
Use `&&` to check Buttons rendering but not `className`

2021-09-11 17:21 UTC, mrakofff commented on src/components/Controls/Controls.module.scss
> +  flex-direction: row;
it is default value, isn't it?

2021-09-11 17:21 UTC, mrakofff commented on src/components/Issues/Issues.module.scss
> +  font-weight: 700;
add scss `variable`

2021-09-11 17:21 UTC, mrakofff commented on src/components/User/User.module.scss
> +  font-weight: 700;
add scss `variable`

2021-09-12 07:29 UTC, MakFill commented on src/components/Button/Button.module.scss
> +  border-radius: .8rem;
done

2021-09-12 07:34 UTC, MakFill commented on src/components/Button/Button.module.scss
> +    transition: 0.3s;
done

2021-09-12 07:36 UTC, MakFill commented on src/components/CommonArea/CardNest/CardNest.module.scss
> +  border-radius: .6rem;
done

2021-09-12 07:38 UTC, MakFill commented on src/components/CommonArea/CardNest/CardNest.module.scss
> +  transition: 0.5s;
done

2021-09-12 07:38 UTC, MakFill commented on src/components/CommonArea/CardNest/CardNest.module.scss
> +    border-radius: .6rem;
done

2021-09-12 07:44 UTC, MakFill commented on src/untils/types/UserType.ts
> +export interface UserType {
done

2021-09-12 07:45 UTC, MakFill commented on src/styles/variables.scss
> +$card-bakside-chosen-color: linear-gradient(45deg,#3993ff 12%,transparent 0,transparent 88%,#3993ff 0), linear-gradient(135deg, transparent 37%,#1a7bf2 0,#1a7bf2 63%, transparent 0), linear-gradient(
done

2021-09-12 07:47 UTC, MakFill commented on src/components/VoteCard/VoteCard.module.scss
> +  font-weight: 600;
done

2021-09-12 07:50 UTC, MakFill commented on src/components/VoteCard/VoteCard.module.scss
> +  transition: 0.3s;
done

2021-09-12 07:53 UTC, MakFill commented on src/components/CommonArea/CardNest/CardNest.tsx
> +  cardStyle?: string;
done

2021-09-12 08:03 UTC, MakFill commented on src/components/CommonArea/Table/Table.tsx
> +          [styles.none]: selectedCardValue || isCardOpened
done

2021-09-12 08:03 UTC, MakFill commented on src/components/Controls/Controls.module.scss
> +  flex-direction: row;
yes

2021-09-12 08:06 UTC, MakFill commented on src/components/Issues/Issues.module.scss
> +  font-weight: 700;
done

2021-09-12 08:07 UTC, MakFill commented on src/components/User/User.module.scss
> +  font-weight: 700;
done

2021-09-12 10:47 UTC, MakFill commented on src/components/VoteCard/PanelVoteCards.tsx
> +            {
const className = useMemo(
      () => `${isCardOpened && styles.unactive} ${score === selectedCardValue  &&  styles.active}`.replaceAll('false', '').trim(),
      [isCardOpened, selectedCardValue]
    );

or

    const classActive = useMemo(
      () => isCardOpened && styles.unactive,
      [isCardOpened]
    );

    const classUnactive = useMemo(
      () => score === selectedCardValue  &&  styles.active,
      [selectedCardValue]
    );
?

2021-09-12 13:25 UTC, mrakofff requested changes

2021-09-12 13:25 UTC, mrakofff commented on src/components/VoteCard/VoteCard.tsx
> +interface IVoteCard {
Could it be with `Props` postfix?

2021-09-12 13:25 UTC, mrakofff commented on src/components/VoteCard/VoteCard.tsx
> +    const classActive = useMemo(
Could you create 1 variable with final className with all conditions using `classnames` lib but not 2 variables and long className value in jsx?

2021-09-12 13:25 UTC, mrakofff commented on src/components/VoteCard/VoteCard.module.scss
> +.card + .card {
replace it with `:not(:first-child)` selector

2021-09-12 13:25 UTC, mrakofff commented on src/components/VoteCard/PanelVoteCards.tsx
> +interface IPanelVoteCards {
Could you add `Props` postfix?

2021-09-12 13:25 UTC, mrakofff commented on src/components/User/User.tsx
> +interface IUser {
Props type/interface should have `Props` postfix. Should `user` be moved to separate interface? will it be reusable?

2021-09-12 13:25 UTC, mrakofff commented on src/components/User/User.module.scss
> +  margin: 0 !important;
why we should use `!important`? could we rethink styles without this flag?

2021-09-12 14:50 UTC, MakFill commented on src/components/VoteCard/VoteCard.module.scss
> +.card + .card {
done

2021-09-12 14:52 UTC, MakFill commented on src/components/User/User.tsx
> +interface IUser {
done

2021-09-12 14:52 UTC, MakFill commented on src/components/User/User.module.scss
> +  margin: 0 !important;
done

2021-09-12 15:15 UTC, MakFill commented on src/components/VoteCard/VoteCard.tsx
> +interface IVoteCard {
done

2021-09-12 15:17 UTC, MakFill commented on src/components/VoteCard/VoteCard.tsx
> +    const classActive = useMemo(
done

2021-09-12 15:17 UTC, MakFill commented on src/components/VoteCard/PanelVoteCards.tsx
> +interface IPanelVoteCards {
done

2021-09-13 15:14 UTC, mrakofff approved these changes

2021-09-13 15:14 UTC, mrakofff commented on src/components/CommonArea/CardNest/CardNest.tsx
> +export const CardNest: React.FC<ICardNest> = ({
add `Props` postfix

2021-09-13 15:14 UTC, mrakofff commented on src/components/CommonArea/CommonArea.tsx
> +export const CommonArea: React.FC<ICommonArea> = ({
`Props` postfix plz

2021-09-13 15:14 UTC, mrakofff commented on src/components/CommonArea/Table/Table.tsx
> +export const Table: React.FC<ITable> = (
`Props` postfix

2021-09-13 15:43 UTC, MakFill commented on src/components/CommonArea/CardNest/CardNest.tsx
> +export const CardNest: React.FC<ICardNest> = ({
done

2021-09-13 15:43 UTC, MakFill commented on src/components/CommonArea/CommonArea.tsx
> +export const CommonArea: React.FC<ICommonArea> = ({
done

2021-09-13 15:43 UTC, MakFill commented on src/components/CommonArea/Table/Table.tsx
> +export const Table: React.FC<ITable> = (
done

2021-09-13 15:48 UTC, merged